Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
""")

if IsDefined(['OS_USING_PIN']) or IsDefined(['OS_USING_SPI']):
    src += ['drv_gpio.c']

if IsDefined(['PKG_USING_EASYFLASH']):
    src += ['drv_easyflash.c']

if IsDefined(['OS_USING_SERIAL']):
    src += ['drv_usart.c']

if IsDefined(['OS_USING_TIMER_DRIVER']):
    src += ['drv_hwtimer.c']
    
if IsDefined(['OS_USING_PWM']):
    src += ['drv_pwm.c']

if IsDefined(['OS_USING_PULSE_ENCODER']):    
    src += ['drv_pulse_encoder.c']

if IsDefined(['OS_USING_SPI']):
    src += ['drv_spi.c']
    
if IsDefined(['OS_USING_I2C', 'BSP_USING_I2C']):
    src += ['drv_i2c.c']

if IsDefined(['OS_USING_QSPI']):
    src += ['drv_qspi.c']

if IsDefined(['NET_USING_LWIP']):
    src += ['drv_eth.c']

if IsDefined(['OS_USING_ADC']):
    src += Glob('drv_adc.c')
    
if IsDefined(['OS_USING_DAC']):
    src += Glob('drv_dac.c')

if IsDefined(['OS_USING_CAN']):
    src += ['drv_can.c']
    
if IsDefined(['OS_USING_LPMGR']):
    src += ['drv_lpmgr.c']
    
if IsDefined(['HAL_SDRAM_MODULE_ENABLED']):
    src += ['drv_sdram.c']
	
if IsDefined(['OS_USING_RTC']):
    src += ['drv_rtc.c']

if IsDefined(['OS_USING_FAL', 'BSP_USING_FLASH']):
    src += ['drv_flash/drv_flash_f3.c']

if IsDefined(['OS_HWCRYPTO_USING_RNG', 'HAL_RNG_MODULE_ENABLED']):
    src += ['drv_crypto_rng.c']

if IsDefined(['OS_HWCRYPTO_USING_CRC', 'HAL_CRC_MODULE_ENABLED']):
    src += ['drv_crypto_crc.c']
    
if IsDefined(['OS_USING_WDG', 'HAL_IWDG_MODULE_ENABLED']):
    src += ['drv_iwdg.c']

if IsDefined(['OS_USING_WDG']):
    src += ['drv_wdg.c']
    
if IsDefined(['OS_USING_SDIO', 'HAL_SD_MODULE_ENABLED']) or IsDefined(['OS_USING_SDIO', 'HAL_MMC_MODULE_ENABLED']):
    src += ['drv_sdio.c']

if IsDefined(['OS_USING_USB_DEVICE', 'HAL_PCD_MODULE_ENABLED']):
    src += ['drv_usbd.c']

if IsDefined(['HAL_SRAM_MODULE_ENABLED']):
    src += ['drv_sram.c']

if IsDefined(['OS_USING_DSI', 'HAL_DSI_MODULE_ENABLED']):
    src += ['drv_dsi.c']
    
if IsDefined(['OS_USING_GRAPHIC', 'HAL_LTDC_MODULE_ENABLED']):
    src += ['drv_lcd.c']

if IsDefined(['OS_USING_SAI', 'HAL_SAI_MODULE_ENABLED']):
    src += ['drv_sai.c']

src += ['drv_common.c']

path =  [pwd]
path += [pwd + '/config']

if IsDefined('HAL_FLASH_MODULE_ENABLED'):
    path += [pwd + '/drv_flash']

group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_GD32E50X'], CPPPATH = path)

Return('group')
