from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_A7600X']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/a7600x.c')
    
if IsDefined(['A7600X_USING_GENERAL_OPS']):
    src += Glob('source/a7600x_general.c')

if IsDefined(['A7600X_USING_NETSERV_OPS']):
    src += Glob('source/a7600x_netserv.c')

if IsDefined(['A7600X_USING_PING_OPS']):
    src += Glob('source/a7600x_ping.c')

if IsDefined(['A7600X_USING_IFCONFIG_OPS']):
    src += Glob('source/a7600x_ifconfig.c')

if IsDefined(['A7600X_USING_NETCONN_OPS']):
    src += Glob('source/a7600x_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')