import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/Device/FM/FM33xx/Source/system_fm33lg0xx.c
FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_gpio.c
FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_cmu.c
FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_dma.c
''')

if IsDefined(['OS_USING_SERIAL','BSP_USING_UART']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_uart.c']

if IsDefined(['OS_USING_SERIAL','BSP_USING_LPUART']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_lpuart.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_flash.c']
    
if IsDefined(['BSP_USING_ATIM']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_atim.c']
    
if IsDefined(['BSP_USING_BSTIM16']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_bstim16.c']

if IsDefined(['BSP_USING_BSTIM32']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_bstim32.c']

if IsDefined(['BSP_USING_GPTIM']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_gptim.c']
    
if IsDefined(['BSP_USING_LPTIM16']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_lptim16.c']
    
if IsDefined(['BSP_USING_LPTIM32']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_lptim32.c']
    
if IsDefined(['BSP_USING_RTCA']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_rtca.c']
    
if IsDefined(['BSP_USING_RTCB']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_rtcb.c']
    
if IsDefined(['BSP_USING_ADC']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_adc.c']
    
if IsDefined(['BSP_USING_WDG']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_iwdt.c']
    
if IsDefined(['BSP_USING_I2C']):
    src += ['FM33LG0xx_FL_Driver/Src/fm33lg0xx_fl_i2c.c']

path = [pwd + '/FM33LG0xx_FL_Driver/Inc',
        pwd + '/CMSIS/Device/FM/FM33xx/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_FM33LG0'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
