import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = []

src += ['GD32E50x_standard_peripheral/Source/gd32e50x_rcu.c']
src += ['GD32E50x_standard_peripheral/Source/gd32e50x_misc.c']
src += ['GD32E50x_standard_peripheral/Source/gd32e50x_gpio.c']
if IsDefined(['OS_USING_PIN']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_exti.c']
#    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_syscfg.c']

if IsDefined(['OS_USING_WDG']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_fwdgt.c']
    
if IsDefined(['OS_USING_SERIAL']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_usart.c']

if IsDefined(['OS_USING_ADC']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_adc.c']

if IsDefined(['OS_USING_DAC']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_dac.c']
    
if IsDefined(['OS_USING_I2C']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_i2c.c']

if IsDefined(['OS_USING_SPI']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_spi.c']
    
if IsDefined(['OS_USING_FAL']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_fmc.c']

if IsDefined(['OS_USING_DMA']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_dma.c']
    
if IsDefined(['BSP_USING_RTC']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_rtc.c']
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_pmu.c']
    
if IsDefined(['BSP_USING_TIMER']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_timer.c']	
    
if IsDefined(['BSP_USING_ETH']):
    src += ['GD32E50x_standard_peripheral/Source/gd32e50x_enet.c']
    
path = [pwd + '/GD32E50x_standard_peripheral/Include',
    pwd + '/CMSIS/GD/GD32E50x/Include',
    pwd + '/CMSIS']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_GD32E50X'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
