import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = Split('''
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rcc.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rcc_ex.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_gpio.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_hsem.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dma.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dma_ex.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_mdma.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pwr.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pwr_ex.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_cortex.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_exti.c
STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_ipcc.c
''')

#src += CMSIS/Device/ST/stm32mp1xx/Source/Templates/system_stm32mp1xx.c

if IsDefined(['HAL_UART_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_uart.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_usart.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_uart_ex.c']

if IsDefined(['HAL_I2C_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_i2c.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_i2c_ex.c']

if IsDefined(['HAL_SPI_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_spi.c']
    
if IsDefined(['HAL_QSPI_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_qspi.c']

if IsDefined(['HAL_HCD_MODULE_ENABLED']) or IsDefined(['HAL_PCD_MODULE_ENABLED']):
   # src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pccard.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pcd.c'] 
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pcd_ex.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_hcd.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_usb.c']

if IsDefined(['HAL_CAN_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_fdcan.c']

if IsDefined(['HAL_TIM_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_tim.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_tim.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_tim_ex.c']

if IsDefined(['HAL_HRTIM_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_hrtim.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_hrtim.c']
    
if IsDefined(['HAL_LPTIM_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_lptim.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_lptim.c']
    
if IsDefined(['HAL_ETH_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_eth.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_eth_ex.c']

if IsDefined(['HAL_ADC_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_adc.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_adc_ex.c']

if IsDefined(['HAL_DAC_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dac.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dac_ex.c']
    
if IsDefined(['HAL_RTC_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rtc.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rtc_ex.c']

if IsDefined(['HAL_IWDG_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_iwdg.c']
    
if IsDefined(['HAL_WWDG_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_wwdg.c']

if IsDefined('HAL_SD_MODULE_ENABLED'):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sd.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sd_ex.c']

if IsDefined('HAL_MMC_MODULE_ENABLED'):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_mmc.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_mmc_ex.c']
    
if IsDefined('HAL_SD_MODULE_ENABLED') or IsDefined('HAL_MMC_MODULE_ENABLED'):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_sdmmc.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_delayblock.c']

if IsDefined(['HAL_SAI_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_i2s.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_i2s_ex.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sai.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sai_ex.c']

if IsDefined(['HAL_NOR_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_nor.c']

if IsDefined(['HAL_NAND_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_nand.c']

if IsDefined(['HAL_SDRAM_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_ll_fmc.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_sdram.c']

#if IsDefined(['HAL_FLASH_MODULE_ENABLED']):
#    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_flash.c']
#    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_flash_ex.c']

if IsDefined(['HAL_LTDC_MODULE_ENABLED']):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_ltdc.c']
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dma2d.c']

if IsDefined('HAL_HSEM_MODULE_ENABLED'):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_hsem.c']
    
if IsDefined('HAL_SPDIFRX_MODULE_ENABLED'):
    src += ['STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_spdifrx.c']
    
path = [pwd + '/STM32MP1xx_HAL_Driver/Inc',
    pwd + '/CMSIS/Device/ST/STM32MP1xx/Include',
    pwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_STM32MP1'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

