import os
from build_tools import *

pwd  = PresentDir()
objs = []

list = os.listdir(pwd)

src	= ['vector_table.c']

objs = AddCodeGroup('drivers', src, depend = ['ARCH_ARM_CORTEX_M'], CPPPATH = [pwd])

Return('objs')
