from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_SIM7020']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/sim7020.c')
    
if IsDefined(['SIM7020_USING_GENERAL_OPS']):
    src += Glob('source/sim7020_general.c')

if IsDefined(['SIM7020_USING_NETSERV_OPS']):
    src += Glob('source/sim7020_netserv.c')

if IsDefined(['SIM7020_USING_PING_OPS']):
    src += Glob('source/sim7020_ping.c')

if IsDefined(['SIM7020_USING_IFCONFIG_OPS']):
    src += Glob('source/sim7020_ifconfig.c')

if IsDefined(['SIM7020_USING_NETCONN_OPS']):
    src += Glob('source/sim7020_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')