
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OD114S_OD_H
#define OD114S_OD_H

#include "cf_data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 od114s_od_valueRangeTest (UNS8 typeValue, void * value);
const indextable * od114s_od_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data od114s_od_Data;
extern UNS16 Digital_In_and_Output_Input_Polarity;		/* Mapped at index 0x2010, subindex 0x01 */
extern UNS16 Digital_In_and_Output_Input_Simulation;		/* Mapped at index 0x2010, subindex 0x02 */
extern UNS16 Digital_In_and_Output_Din1_Function;		/* Mapped at index 0x2010, subindex 0x03 */
extern UNS16 Digital_In_and_Output_Din2_Function;		/* Mapped at index 0x2010, subindex 0x04 */
extern UNS16 Digital_In_and_Output_Din3_Function;		/* Mapped at index 0x2010, subindex 0x05 */
extern UNS16 Digital_In_and_Output_Din4_Function;		/* Mapped at index 0x2010, subindex 0x06 */
extern UNS16 Digital_In_and_Output_Din5_Function;		/* Mapped at index 0x2010, subindex 0x07 */
extern UNS16 Digital_In_and_Output_Din6_Function;		/* Mapped at index 0x2010, subindex 0x08 */
extern UNS16 Digital_In_and_Output_Din7_Function;		/* Mapped at index 0x2010, subindex 0x09 */
extern UNS16 Digital_In_and_Output_Input_Status;		/* Mapped at index 0x2010, subindex 0x0A */
extern UNS16 Digital_In_and_Output_Input_Virtual_Status;		/* Mapped at index 0x2010, subindex 0x0B */
extern UNS16 Digital_In_and_Output_Input_Sys_Status;		/* Mapped at index 0x2010, subindex 0x0C */
extern UNS16 Digital_In_and_Output_Output_Polarity;		/* Mapped at index 0x2010, subindex 0x0D */
extern UNS16 Digital_In_and_Output_Output_Simulation;		/* Mapped at index 0x2010, subindex 0x0E */
extern UNS16 Digital_In_and_Output_Dout1_Function;		/* Mapped at index 0x2010, subindex 0x0F */
extern UNS16 Digital_In_and_Output_Dout2_Function;		/* Mapped at index 0x2010, subindex 0x10 */
extern UNS16 Digital_In_and_Output_Dout3_Function;		/* Mapped at index 0x2010, subindex 0x11 */
extern UNS16 Digital_In_and_Output_Dout4_Function;		/* Mapped at index 0x2010, subindex 0x12 */
extern UNS16 Digital_In_and_Output_Dout5_Function;		/* Mapped at index 0x2010, subindex 0x13 */
extern UNS16 Digital_In_and_Output_Output_Status;		/* Mapped at index 0x2010, subindex 0x14 */
extern UNS16 Digital_In_and_Output_Output_Virtual_Status;		/* Mapped at index 0x2010, subindex 0x15 */
extern UNS16 Digital_In_and_Output_Output_Sys_Status;		/* Mapped at index 0x2010, subindex 0x16 */
extern UNS8 Digital_In_and_Output_Compatibility_Entry1;		/* Mapped at index 0x2010, subindex 0x17 */
extern UNS8 Digital_In_and_Output_Compatibility_Entry2;		/* Mapped at index 0x2010, subindex 0x18 */
extern UNS8 Digital_In_and_Output_Compatibility_Entry3;		/* Mapped at index 0x2010, subindex 0x19 */
extern UNS8 Digital_In_and_Output_Compatibility_Entry4;		/* Mapped at index 0x2010, subindex 0x1A */
extern UNS8 Digital_In_and_Output_Compatibility_Entry5;		/* Mapped at index 0x2010, subindex 0x1B */
extern UNS8 Digital_In_and_Output_Compatibility_Entry6;		/* Mapped at index 0x2010, subindex 0x1C */
extern UNS16 Digital_In_and_Output_Din8_Function;		/* Mapped at index 0x2010, subindex 0x1D */
extern UNS16 Digital_In_and_Output_Dout6_Function;		/* Mapped at index 0x2010, subindex 0x1E */
extern UNS16 Digital_In_and_Output_Dout7_Function;		/* Mapped at index 0x2010, subindex 0x1F */
extern UNS8 ADC_Real_Data_Compatibility_Entry1;		/* Mapped at index 0x2501, subindex 0x01 */
extern UNS8 ADC_Real_Data_Compatibility_Entry2;		/* Mapped at index 0x2501, subindex 0x02 */
extern UNS8 ADC_Real_Data_Compatibility_Entry3;		/* Mapped at index 0x2501, subindex 0x03 */
extern UNS16 ADC_Real_Data_ADC1_Data0;		/* Mapped at index 0x2501, subindex 0x04 */
extern UNS16 ADC_Real_Data_ADC2_Data0;		/* Mapped at index 0x2501, subindex 0x05 */
extern UNS16 ADC_Real_Data_ADC1_Data1;		/* Mapped at index 0x2501, subindex 0x06 */
extern UNS16 ADC_Real_Data_ADC2_Data1;		/* Mapped at index 0x2501, subindex 0x07 */
extern UNS16 ADC_Real_Data_ADC1_Data2;		/* Mapped at index 0x2501, subindex 0x08 */
extern UNS16 ADC_Real_Data_ADC2_Data2;		/* Mapped at index 0x2501, subindex 0x09 */
extern UNS16 ADC_Real_Data_ADC_Temperature;		/* Mapped at index 0x2501, subindex 0x0A */
extern UNS16 ADC_Real_Data_ADC_DCBUS;		/* Mapped at index 0x2501, subindex 0x0B */
extern UNS16 ADC_Real_Data_ADC1_Data3;		/* Mapped at index 0x2501, subindex 0x0C */
extern UNS16 ADC_Real_Data_ADC1_Data4;		/* Mapped at index 0x2501, subindex 0x0D */
extern UNS16 Analog_Input_Config_Analog1_Filter;		/* Mapped at index 0x2502, subindex 0x01 */
extern INTEGER16 Analog_Input_Config_Analog1_Dead;		/* Mapped at index 0x2502, subindex 0x02 */
extern INTEGER16 Analog_Input_Config_Analog1_Offset;		/* Mapped at index 0x2502, subindex 0x03 */
extern UNS16 Analog_Input_Config_Analog2_Filter;		/* Mapped at index 0x2502, subindex 0x04 */
extern INTEGER16 Analog_Input_Config_Analog2_Dead;		/* Mapped at index 0x2502, subindex 0x05 */
extern INTEGER16 Analog_Input_Config_Analog2_Offset;		/* Mapped at index 0x2502, subindex 0x06 */
extern UNS8 Analog_Input_Config_Analog_Speed_Control;		/* Mapped at index 0x2502, subindex 0x07 */
extern UNS8 Analog_Input_Config_Analog_Torque_Control;		/* Mapped at index 0x2502, subindex 0x08 */
extern UNS8 Analog_Input_Config_Analog_Max_Torque_Control;		/* Mapped at index 0x2502, subindex 0x09 */
extern INTEGER16 Analog_Input_Config_Analog_Speed_Factor;		/* Mapped at index 0x2502, subindex 0x0A */
extern INTEGER16 Analog_Input_Config_Analog_Torque_Factor;		/* Mapped at index 0x2502, subindex 0x0B */
extern INTEGER16 Analog_Input_Config_Analog_Max_Torque_Factor;		/* Mapped at index 0x2502, subindex 0x0C */
extern INTEGER16 Analog_Input_Config_Analog_Dead_High;		/* Mapped at index 0x2502, subindex 0x0D */
extern INTEGER16 Analog_Input_Config_Analog_Dead_Low;		/* Mapped at index 0x2502, subindex 0x0E */
extern INTEGER16 Analog_Input_Config_Analog1_Value;		/* Mapped at index 0x2502, subindex 0x0F */
extern INTEGER16 Analog_Input_Config_Analog2_Value;		/* Mapped at index 0x2502, subindex 0x10 */
extern INTEGER16 Pulse_Control_Gear_Factor;		/* Mapped at index 0x2508, subindex 0x01 */
extern UNS16 Pulse_Control_Gear_Devider;		/* Mapped at index 0x2508, subindex 0x02 */
extern UNS8 Pulse_Control_Pulse_Mode;		/* Mapped at index 0x2508, subindex 0x03 */
extern INTEGER32 Pulse_Control_Gear_Master_Counter;		/* Mapped at index 0x2508, subindex 0x04 */
extern INTEGER32 Pulse_Control_Gear_Slave_Counter;		/* Mapped at index 0x2508, subindex 0x05 */
extern UNS16 Pulse_Control_Pulse_Filter;		/* Mapped at index 0x2508, subindex 0x06 */
extern INTEGER16 Pulse_Control_Gear_Remainder;		/* Mapped at index 0x2508, subindex 0x07 */
extern UNS16 Pulse_Control_Pulse_Frequency_Check;		/* Mapped at index 0x2508, subindex 0x08 */
extern UNS16 Pulse_Control_Position_Reach_Time_Window;		/* Mapped at index 0x2508, subindex 0x09 */
extern UNS8 Pulse_Control_Master_Capture_Control;		/* Mapped at index 0x2508, subindex 0x0A */
extern UNS8 Pulse_Control_Compatibility_Entry1;		/* Mapped at index 0x2508, subindex 0x0B */
extern INTEGER16 Pulse_Control_Pulse_Master_Frequency;		/* Mapped at index 0x2508, subindex 0x0C */
extern INTEGER16 Pulse_Control_Pulse_Slave_Frequency;		/* Mapped at index 0x2508, subindex 0x0D */
extern UNS8 Pulse_Control_Compatibility_Entry2;		/* Mapped at index 0x2508, subindex 0x0E */
extern INTEGER32 Pulse_Control_Master_Capture_Data;		/* Mapped at index 0x2508, subindex 0x0F */
extern UNS16 Error_Status;		/* Mapped at index 0x2601, subindex 0x00*/
extern UNS16 Error_Status2;		/* Mapped at index 0x2602, subindex 0x00*/
extern UNS8 ECAN_Baudrate;		/* Mapped at index 0x2F81, subindex 0x00*/
extern UNS16 RS232_Bandrate;		/* Mapped at index 0x2FE0, subindex 0x00*/
extern UNS16 RS485_Bandrate;		/* Mapped at index 0x2FE2, subindex 0x00*/
extern UNS8 ECAN_Parameters_Setting_ECAN_Sync_Cycle;		/* Mapped at index 0x3011, subindex 0x01 */
extern UNS8 ECAN_Parameters_Setting_ECAN_Sync_Clock;		/* Mapped at index 0x3011, subindex 0x02 */
extern UNS8 ECAN_Parameters_Setting_ECAN_Flags;		/* Mapped at index 0x3011, subindex 0x03 */
extern INTEGER16 ECAN_Parameters_Setting_ECAN_Sync_Data;		/* Mapped at index 0x3011, subindex 0x04 */
extern INTEGER32 absolute_position_of_motor;		/* Mapped at index 0x6004, subindex 0x00*/
extern INTEGER16 Abort_Connection_Mode;		/* Mapped at index 0x6007, subindex 0x00*/
extern UNS16 error_code_for_DS301;		/* Mapped at index 0x603F, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER16 Quick_stop_option_code;		/* Mapped at index 0x605A, subindex 0x00*/
extern INTEGER16 Shutdown_Stop_Mode;		/* Mapped at index 0x605B, subindex 0x00*/
extern INTEGER16 Disable_Stop_Mode;		/* Mapped at index 0x605C, subindex 0x00*/
extern INTEGER16 Halt_Mode;		/* Mapped at index 0x605D, subindex 0x00*/
extern INTEGER16 Fault_reaction_option_code;		/* Mapped at index 0x605E, subindex 0x00*/
extern INTEGER8 Modes_of_operation;		/* Mapped at index 0x6060, subindex 0x00*/
extern INTEGER8 Modes_of_operation_display;		/* Mapped at index 0x6061, subindex 0x00*/
extern INTEGER32 Position_actual_value_;		/* Mapped at index 0x6063, subindex 0x00*/
extern INTEGER32 Position_actual_value;		/* Mapped at index 0x6064, subindex 0x00*/
extern UNS32 Maximal_following_error;		/* Mapped at index 0x6065, subindex 0x00*/
extern UNS32 Position_window;		/* Mapped at index 0x6067, subindex 0x00*/
extern UNS16 Position_window_time;		/* Mapped at index 0x6068, subindex 0x00*/
extern INTEGER32 Velocity_demand_value;		/* Mapped at index 0x606B, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern INTEGER16 Target_torque;		/* Mapped at index 0x6071, subindex 0x00*/
extern UNS16 Max_Torque;		/* Mapped at index 0x6072, subindex 0x00*/
extern UNS16 Max_current;		/* Mapped at index 0x6073, subindex 0x00*/
extern UNS32 Rated_Current;		/* Mapped at index 0x6075, subindex 0x00*/
extern UNS32 Rated_Torque;		/* Mapped at index 0x6076, subindex 0x00*/
extern INTEGER16 Actual_Torque;		/* Mapped at index 0x6077, subindex 0x00*/
extern INTEGER16 Current_actual_value;		/* Mapped at index 0x6078, subindex 0x00*/
extern UNS32 Real_DCBUS_mV;		/* Mapped at index 0x6079, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern INTEGER32 Home_offset;		/* Mapped at index 0x607C, subindex 0x00*/
extern INTEGER32 Software_position_limit_Minimal_position_limit;		/* Mapped at index 0x607D, subindex 0x01 */
extern INTEGER32 Software_position_limit_Maximal_position_limit;		/* Mapped at index 0x607D, subindex 0x02 */
extern UNS8 Polarity;		/* Mapped at index 0x607E, subindex 0x00*/
extern UNS32 Maximal_profile_velocity;		/* Mapped at index 0x607F, subindex 0x00*/
extern UNS16 Max_Speed_RPM;		/* Mapped at index 0x6080, subindex 0x00*/
extern UNS32 Profile_velocity;		/* Mapped at index 0x6081, subindex 0x00*/
extern UNS32 Profile_acceleration;		/* Mapped at index 0x6083, subindex 0x00*/
extern UNS32 Profile_deceleration;		/* Mapped at index 0x6084, subindex 0x00*/
extern UNS32 Quick_stop_deceleration;		/* Mapped at index 0x6085, subindex 0x00*/
extern INTEGER8 Homing_method;		/* Mapped at index 0x6098, subindex 0x00*/
extern UNS32 Homing_acceleration;		/* Mapped at index 0x609A, subindex 0x00*/
extern INTEGER16 Interpolation_sub_mode_select;		/* Mapped at index 0x60C0, subindex 0x00*/
extern INTEGER32 Interpolation_data_record_Interpolation_data_record_x1_1;		/* Mapped at index 0x60C1, subindex 0x01 */
extern INTEGER32 Interpolation_data_record_Interpolation_data_record_x1_2;		/* Mapped at index 0x60C1, subindex 0x02 */
extern UNS8 Interpolation_time_period_Interpolation_time_period_Interpolation_time_units_1;		/* Mapped at index 0x60C2, subindex 0x01 */
extern INTEGER8 Interpolation_time_period_Interpolation_time_period_Interpolation_time_index;		/* Mapped at index 0x60C2, subindex 0x02 */
extern UNS8 Interpolation_sync_definition_Interpolation_sync_definition_Synchronize_on_group_1;		/* Mapped at index 0x60C3, subindex 0x01 */
extern UNS8 Interpolation_sync_definition_Interpolation_sync_definition_ip_sync_every_n_event;		/* Mapped at index 0x60C3, subindex 0x02 */
extern UNS32 Interpolation_data_configuration_Interpolation_data_configuration_Maximum_buffer_size_1;		/* Mapped at index 0x60C4, subindex 0x01 */
extern UNS32 Interpolation_data_configuration_Interpolation_data_configuration_Actual_buffer_size;		/* Mapped at index 0x60C4, subindex 0x02 */
extern UNS8 Interpolation_data_configuration_Interpolation_data_configuration_Buffer_organization;		/* Mapped at index 0x60C4, subindex 0x03 */
extern UNS16 Interpolation_data_configuration_Interpolation_data_configuration_Buffer_position;		/* Mapped at index 0x60C4, subindex 0x04 */
extern UNS8 Interpolation_data_configuration_Interpolation_data_configuration_Size_of_data_record;		/* Mapped at index 0x60C4, subindex 0x05 */
extern UNS8 Interpolation_data_configuration_Value_Description_Buffer_clear;		/* Mapped at index 0x60C4, subindex 0x06 */
extern INTEGER32 Following_error_actual_value;		/* Mapped at index 0x60F4, subindex 0x00*/
extern INTEGER16 Current_control_parameter_set_Current_regulator_P_gain;		/* Mapped at index 0x60F6, subindex 0x01 */
extern INTEGER16 Current_control_parameter_set_Current_regulator_I_gain;		/* Mapped at index 0x60F6, subindex 0x02 */
extern INTEGER32 Position_demand_value;		/* Mapped at index 0x60FC, subindex 0x00*/
extern UNS32 Digital_inputs;		/* Mapped at index 0x60FD, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/
extern UNS16 Motor_data_Continous_current_limit;		/* Mapped at index 0x6410, subindex 0x01 */
extern UNS16 Motor_data_Output_current_limit;		/* Mapped at index 0x6410, subindex 0x02 */
extern UNS8 Motor_data_Pole_pair_number;		/* Mapped at index 0x6410, subindex 0x03 */
extern UNS16 Motor_data_Maximal_speed_in_current_mode;		/* Mapped at index 0x6410, subindex 0x04 */
extern UNS16 Motor_data_Thermal_time_constant_winding;		/* Mapped at index 0x6410, subindex 0x05 */
extern UNS8 Drive_manufacturer[30];		/* Mapped at index 0x6504, subindex 0x00*/

#endif // OD114S_OD_H
