
/* File generated by gen_cfile.py. Should not be modified. */

#include "od114s_od.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Digital_In_and_Output_Input_Polarity = 0xFFFF;		/* Mapped at index 0x2010, subindex 0x01 */
UNS16 Digital_In_and_Output_Input_Simulation = 0x0;		/* Mapped at index 0x2010, subindex 0x02 */
UNS16 Digital_In_and_Output_Din1_Function = 0x1;		/* Mapped at index 0x2010, subindex 0x03 */
UNS16 Digital_In_and_Output_Din2_Function = 0x2;		/* Mapped at index 0x2010, subindex 0x04 */
UNS16 Digital_In_and_Output_Din3_Function = 0x4;		/* Mapped at index 0x2010, subindex 0x05 */
UNS16 Digital_In_and_Output_Din4_Function = 0x8;		/* Mapped at index 0x2010, subindex 0x06 */
UNS16 Digital_In_and_Output_Din5_Function = 0x10;		/* Mapped at index 0x2010, subindex 0x07 */
UNS16 Digital_In_and_Output_Din6_Function = 0x20;		/* Mapped at index 0x2010, subindex 0x08 */
UNS16 Digital_In_and_Output_Din7_Function = 0x40;		/* Mapped at index 0x2010, subindex 0x09 */
UNS16 Digital_In_and_Output_Input_Status = 0x0;		/* Mapped at index 0x2010, subindex 0x0A */
UNS16 Digital_In_and_Output_Input_Virtual_Status = 0x0;		/* Mapped at index 0x2010, subindex 0x0B */
UNS16 Digital_In_and_Output_Input_Sys_Status = 0x0;		/* Mapped at index 0x2010, subindex 0x0C */
UNS16 Digital_In_and_Output_Output_Polarity = 0xFFFF;		/* Mapped at index 0x2010, subindex 0x0D */
UNS16 Digital_In_and_Output_Output_Simulation = 0x0;		/* Mapped at index 0x2010, subindex 0x0E */
UNS16 Digital_In_and_Output_Dout1_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x0F */
UNS16 Digital_In_and_Output_Dout2_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x10 */
UNS16 Digital_In_and_Output_Dout3_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x11 */
UNS16 Digital_In_and_Output_Dout4_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x12 */
UNS16 Digital_In_and_Output_Dout5_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x13 */
UNS16 Digital_In_and_Output_Output_Status = 0x0;		/* Mapped at index 0x2010, subindex 0x14 */
UNS16 Digital_In_and_Output_Output_Virtual_Status = 0x20;		/* Mapped at index 0x2010, subindex 0x15 */
UNS16 Digital_In_and_Output_Output_Sys_Status = 0x20;		/* Mapped at index 0x2010, subindex 0x16 */
UNS8 Digital_In_and_Output_Compatibility_Entry1 = 0x0;		/* Mapped at index 0x2010, subindex 0x17 */
UNS8 Digital_In_and_Output_Compatibility_Entry2 = 0x0;		/* Mapped at index 0x2010, subindex 0x18 */
UNS8 Digital_In_and_Output_Compatibility_Entry3 = 0x0;		/* Mapped at index 0x2010, subindex 0x19 */
UNS8 Digital_In_and_Output_Compatibility_Entry4 = 0x0;		/* Mapped at index 0x2010, subindex 0x1A */
UNS8 Digital_In_and_Output_Compatibility_Entry5 = 0x0;		/* Mapped at index 0x2010, subindex 0x1B */
UNS8 Digital_In_and_Output_Compatibility_Entry6 = 0x0;		/* Mapped at index 0x2010, subindex 0x1C */
UNS16 Digital_In_and_Output_Din8_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x1D */
UNS16 Digital_In_and_Output_Dout6_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x1E */
UNS16 Digital_In_and_Output_Dout7_Function = 0x0;		/* Mapped at index 0x2010, subindex 0x1F */
UNS8 ADC_Real_Data_Compatibility_Entry1 = 0x0;		/* Mapped at index 0x2501, subindex 0x01 */
UNS8 ADC_Real_Data_Compatibility_Entry2 = 0x0;		/* Mapped at index 0x2501, subindex 0x02 */
UNS8 ADC_Real_Data_Compatibility_Entry3 = 0x0;		/* Mapped at index 0x2501, subindex 0x03 */
UNS16 ADC_Real_Data_ADC1_Data0 = 0x0;		/* Mapped at index 0x2501, subindex 0x04 */
UNS16 ADC_Real_Data_ADC2_Data0 = 0x0;		/* Mapped at index 0x2501, subindex 0x05 */
UNS16 ADC_Real_Data_ADC1_Data1 = 0x0;		/* Mapped at index 0x2501, subindex 0x06 */
UNS16 ADC_Real_Data_ADC2_Data1 = 0x0;		/* Mapped at index 0x2501, subindex 0x07 */
UNS16 ADC_Real_Data_ADC1_Data2 = 0x0;		/* Mapped at index 0x2501, subindex 0x08 */
UNS16 ADC_Real_Data_ADC2_Data2 = 0x0;		/* Mapped at index 0x2501, subindex 0x09 */
UNS16 ADC_Real_Data_ADC_Temperature = 0x0;		/* Mapped at index 0x2501, subindex 0x0A */
UNS16 ADC_Real_Data_ADC_DCBUS = 0x0;		/* Mapped at index 0x2501, subindex 0x0B */
UNS16 ADC_Real_Data_ADC1_Data3 = 0x0;		/* Mapped at index 0x2501, subindex 0x0C */
UNS16 ADC_Real_Data_ADC1_Data4 = 0x0;		/* Mapped at index 0x2501, subindex 0x0D */
UNS16 Analog_Input_Config_Analog1_Filter = 0x3;		/* Mapped at index 0x2502, subindex 0x01 */
INTEGER16 Analog_Input_Config_Analog1_Dead = 0x0;		/* Mapped at index 0x2502, subindex 0x02 */
INTEGER16 Analog_Input_Config_Analog1_Offset = 0x0;		/* Mapped at index 0x2502, subindex 0x03 */
UNS16 Analog_Input_Config_Analog2_Filter = 0x3;		/* Mapped at index 0x2502, subindex 0x04 */
INTEGER16 Analog_Input_Config_Analog2_Dead = 0x0;		/* Mapped at index 0x2502, subindex 0x05 */
INTEGER16 Analog_Input_Config_Analog2_Offset = 0x0;		/* Mapped at index 0x2502, subindex 0x06 */
UNS8 Analog_Input_Config_Analog_Speed_Control = 0x0;		/* Mapped at index 0x2502, subindex 0x07 */
UNS8 Analog_Input_Config_Analog_Torque_Control = 0x0;		/* Mapped at index 0x2502, subindex 0x08 */
UNS8 Analog_Input_Config_Analog_Max_Torque_Control = 0x0;		/* Mapped at index 0x2502, subindex 0x09 */
INTEGER16 Analog_Input_Config_Analog_Speed_Factor = 0x0;		/* Mapped at index 0x2502, subindex 0x0A */
INTEGER16 Analog_Input_Config_Analog_Torque_Factor = 0x0;		/* Mapped at index 0x2502, subindex 0x0B */
INTEGER16 Analog_Input_Config_Analog_Max_Torque_Factor = 0x0;		/* Mapped at index 0x2502, subindex 0x0C */
INTEGER16 Analog_Input_Config_Analog_Dead_High = 0x0;		/* Mapped at index 0x2502, subindex 0x0D */
INTEGER16 Analog_Input_Config_Analog_Dead_Low = 0x0;		/* Mapped at index 0x2502, subindex 0x0E */
INTEGER16 Analog_Input_Config_Analog1_Value = 0x0;		/* Mapped at index 0x2502, subindex 0x0F */
INTEGER16 Analog_Input_Config_Analog2_Value = 0x0;		/* Mapped at index 0x2502, subindex 0x10 */
INTEGER16 Pulse_Control_Gear_Factor = 0x3E8;		/* Mapped at index 0x2508, subindex 0x01 */
UNS16 Pulse_Control_Gear_Devider = 0x3E8;		/* Mapped at index 0x2508, subindex 0x02 */
UNS8 Pulse_Control_Pulse_Mode = 0x0;		/* Mapped at index 0x2508, subindex 0x03 */
INTEGER32 Pulse_Control_Gear_Master_Counter = 0x0;		/* Mapped at index 0x2508, subindex 0x04 */
INTEGER32 Pulse_Control_Gear_Slave_Counter = 0x0;		/* Mapped at index 0x2508, subindex 0x05 */
UNS16 Pulse_Control_Pulse_Filter = 0x3;		/* Mapped at index 0x2508, subindex 0x06 */
INTEGER16 Pulse_Control_Gear_Remainder = 0x0;		/* Mapped at index 0x2508, subindex 0x07 */
UNS16 Pulse_Control_Pulse_Frequency_Check = 0x258;		/* Mapped at index 0x2508, subindex 0x08 */
UNS16 Pulse_Control_Position_Reach_Time_Window = 0xA;		/* Mapped at index 0x2508, subindex 0x09 */
UNS8 Pulse_Control_Master_Capture_Control = 0x0;		/* Mapped at index 0x2508, subindex 0x0A */
UNS8 Pulse_Control_Compatibility_Entry1 = 0x0;		/* Mapped at index 0x2508, subindex 0x0B */
INTEGER16 Pulse_Control_Pulse_Master_Frequency = 0x0;		/* Mapped at index 0x2508, subindex 0x0C */
INTEGER16 Pulse_Control_Pulse_Slave_Frequency = 0x3E8;		/* Mapped at index 0x2508, subindex 0x0D */
UNS8 Pulse_Control_Compatibility_Entry2 = 0x0;		/* Mapped at index 0x2508, subindex 0x0E */
INTEGER32 Pulse_Control_Master_Capture_Data = 0x0;		/* Mapped at index 0x2508, subindex 0x0F */
UNS16 Error_Status = 0x0;		/* Mapped at index 0x2601, subindex 0x00 */
UNS16 Error_Status2 = 0x0;		/* Mapped at index 0x2602, subindex 0x00 */
UNS8 ECAN_Baudrate = 0x32;		/* Mapped at index 0x2F81, subindex 0x00 */
UNS16 RS232_Bandrate = 0x10E;		/* Mapped at index 0x2FE0, subindex 0x00 */
UNS16 RS485_Bandrate = 0x21C;		/* Mapped at index 0x2FE2, subindex 0x00 */
UNS8 ECAN_Parameters_Setting_ECAN_Sync_Cycle = 0x2;		/* Mapped at index 0x3011, subindex 0x01 */
UNS8 ECAN_Parameters_Setting_ECAN_Sync_Clock = 0x0;		/* Mapped at index 0x3011, subindex 0x02 */
UNS8 ECAN_Parameters_Setting_ECAN_Flags = 0x0;		/* Mapped at index 0x3011, subindex 0x03 */
INTEGER16 ECAN_Parameters_Setting_ECAN_Sync_Data = 0x0;		/* Mapped at index 0x3011, subindex 0x04 */
INTEGER32 absolute_position_of_motor = 0x0;		/* Mapped at index 0x6004, subindex 0x00 */
INTEGER16 Abort_Connection_Mode = 0x0;		/* Mapped at index 0x6007, subindex 0x00 */
UNS16 error_code_for_DS301 = 0x0;		/* Mapped at index 0x603F, subindex 0x00 */
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER16 Quick_stop_option_code = 0x0;		/* Mapped at index 0x605A, subindex 0x00 */
INTEGER16 Shutdown_Stop_Mode = 0x0;		/* Mapped at index 0x605B, subindex 0x00 */
INTEGER16 Disable_Stop_Mode = 0x0;		/* Mapped at index 0x605C, subindex 0x00 */
INTEGER16 Halt_Mode = 0x0;		/* Mapped at index 0x605D, subindex 0x00 */
INTEGER16 Fault_reaction_option_code = 0x0;		/* Mapped at index 0x605E, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_actual_value_ = 0x0;		/* Mapped at index 0x6063, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
UNS32 Maximal_following_error = 0x0;		/* Mapped at index 0x6065, subindex 0x00 */
UNS32 Position_window = 0x0;		/* Mapped at index 0x6067, subindex 0x00 */
UNS16 Position_window_time = 0x0;		/* Mapped at index 0x6068, subindex 0x00 */
INTEGER32 Velocity_demand_value = 0x0;		/* Mapped at index 0x606B, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER16 Target_torque = 0x0;		/* Mapped at index 0x6071, subindex 0x00 */
UNS16 Max_Torque = 0x0;		/* Mapped at index 0x6072, subindex 0x00 */
UNS16 Max_current = 0x0;		/* Mapped at index 0x6073, subindex 0x00 */
UNS32 Rated_Current = 0x0;		/* Mapped at index 0x6075, subindex 0x00 */
UNS32 Rated_Torque = 0x0;		/* Mapped at index 0x6076, subindex 0x00 */
INTEGER16 Actual_Torque = 0x0;		/* Mapped at index 0x6077, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
UNS32 Real_DCBUS_mV = 0x0;		/* Mapped at index 0x6079, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Home_offset = 0x0;		/* Mapped at index 0x607C, subindex 0x00 */
INTEGER32 Software_position_limit_Minimal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x01 */
INTEGER32 Software_position_limit_Maximal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x02 */
UNS8 Polarity = 0x0;		/* Mapped at index 0x607E, subindex 0x00 */
UNS32 Maximal_profile_velocity = 0x5555554;		/* Mapped at index 0x607F, subindex 0x00 */
UNS16 Max_Speed_RPM = 0x0;		/* Mapped at index 0x6080, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
UNS32 Profile_acceleration = 0x186A0;		/* Mapped at index 0x6083, subindex 0x00 */
UNS32 Profile_deceleration = 0x186A0;		/* Mapped at index 0x6084, subindex 0x00 */
UNS32 Quick_stop_deceleration = 0x186A0;		/* Mapped at index 0x6085, subindex 0x00 */
INTEGER8 Homing_method = 0x0;		/* Mapped at index 0x6098, subindex 0x00 */
UNS32 Homing_acceleration = 0x0;		/* Mapped at index 0x609A, subindex 0x00 */
INTEGER16 Interpolation_sub_mode_select = 0x0;		/* Mapped at index 0x60C0, subindex 0x00 */
INTEGER32 Interpolation_data_record_Interpolation_data_record_x1_1 = 0x0;		/* Mapped at index 0x60C1, subindex 0x01 */
INTEGER32 Interpolation_data_record_Interpolation_data_record_x1_2 = 0x0;		/* Mapped at index 0x60C1, subindex 0x02 */
UNS8 Interpolation_time_period_Interpolation_time_period_Interpolation_time_units_1 = 0x1;		/* Mapped at index 0x60C2, subindex 0x01 */
INTEGER8 Interpolation_time_period_Interpolation_time_period_Interpolation_time_index = 0x0;		/* Mapped at index 0x60C2, subindex 0x02 */
UNS8 Interpolation_sync_definition_Interpolation_sync_definition_Synchronize_on_group_1 = 0x0;		/* Mapped at index 0x60C3, subindex 0x01 */
UNS8 Interpolation_sync_definition_Interpolation_sync_definition_ip_sync_every_n_event = 0x1;		/* Mapped at index 0x60C3, subindex 0x02 */
UNS32 Interpolation_data_configuration_Interpolation_data_configuration_Maximum_buffer_size_1 = 0x1;		/* Mapped at index 0x60C4, subindex 0x01 */
UNS32 Interpolation_data_configuration_Interpolation_data_configuration_Actual_buffer_size = 0x0;		/* Mapped at index 0x60C4, subindex 0x02 */
UNS8 Interpolation_data_configuration_Interpolation_data_configuration_Buffer_organization = 0x0;		/* Mapped at index 0x60C4, subindex 0x03 */
UNS16 Interpolation_data_configuration_Interpolation_data_configuration_Buffer_position = 0x0;		/* Mapped at index 0x60C4, subindex 0x04 */
UNS8 Interpolation_data_configuration_Interpolation_data_configuration_Size_of_data_record = 0x1;		/* Mapped at index 0x60C4, subindex 0x05 */
UNS8 Interpolation_data_configuration_Value_Description_Buffer_clear = 0x0;		/* Mapped at index 0x60C4, subindex 0x06 */
INTEGER32 Following_error_actual_value = 0x0;		/* Mapped at index 0x60F4, subindex 0x00 */
INTEGER16 Current_control_parameter_set_Current_regulator_P_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x01 */
INTEGER16 Current_control_parameter_set_Current_regulator_I_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x02 */
INTEGER32 Position_demand_value = 0x0;		/* Mapped at index 0x60FC, subindex 0x00 */
UNS32 Digital_inputs = 0x0;		/* Mapped at index 0x60FD, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */
UNS16 Motor_data_Continous_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x01 */
UNS16 Motor_data_Output_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x02 */
UNS8 Motor_data_Pole_pair_number = 0x0;		/* Mapped at index 0x6410, subindex 0x03 */
UNS16 Motor_data_Maximal_speed_in_current_mode = 0x0;		/* Mapped at index 0x6410, subindex 0x04 */
UNS16 Motor_data_Thermal_time_constant_winding = 0x0;		/* Mapped at index 0x6410, subindex 0x05 */
UNS8 Drive_manufacturer[30] = "Kinco Electric (Shenzhen) Ltd.";		/* Mapped at index 0x6504, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 od114s_od_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 od114s_od_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 od114s_od_iam_a_slave = 0;

TIMER_HANDLE od114s_od_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 od114s_od_obj1000 = 0x20192;	/* 131474 */
                    subindex od114s_od_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&od114s_od_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 od114s_od_obj1001 = 0x0;	/* 0 */
                    subindex od114s_od_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 od114s_od_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 od114s_od_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t od114s_od_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex od114s_od_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&od114s_od_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 od114s_od_obj1005 = 0x80000080;	/* 2147483776 */
                    ODCallback_t od114s_od_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex od114s_od_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 od114s_od_obj1006 = 0x7D0;	/* 2000 */
                    ODCallback_t od114s_od_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex od114s_od_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1006 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 od114s_od_obj1008[10] = "";
                    subindex od114s_od_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&od114s_od_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 od114s_od_obj1009[10] = "";
                    subindex od114s_od_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&od114s_od_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 od114s_od_obj100A[10] = "";
                    subindex od114s_od_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&od114s_od_obj100A }
                     };

/* index 0x100B :   Device ID. */
                    UNS8 od114s_od_obj100B = 0x1;	/* 1 */
                    subindex od114s_od_Index100B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&od114s_od_obj100B }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 od114s_od_obj100C = 0x3E8;	/* 1000 */
                    subindex od114s_od_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&od114s_od_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 od114s_od_obj100D = 0x3;	/* 3 */
                    subindex od114s_od_Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&od114s_od_obj100D }
                     };

/* index 0x100E :   Node Guarding ID. */
                    UNS32 od114s_od_obj100E = 0x700;	/* 1792 */
                    subindex od114s_od_Index100E[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj100E }
                     };

/* index 0x1010 :   Store parameters. */
                    UNS8 od114s_od_highestSubIndex_obj1010 = 2; /* number of subindex - 1*/
                    UNS32 od114s_od_obj1010_Save_All_Parameters = 0x65766173;	/* 1702257011 */
                    UNS32 od114s_od_obj1010_Save_Communication_Parameters = 0x65766173;	/* 1702257011 */
                    subindex od114s_od_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1010_Save_Communication_Parameters }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 od114s_od_highestSubIndex_obj1011 = 1; /* number of subindex - 1*/
                    UNS32 od114s_od_obj1011_Restore_All_Default_Parameters = 0x64616F6C;	/* 1684107116 */
                    subindex od114s_od_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1011_Restore_All_Default_Parameters }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 od114s_od_obj1014 = 0x80;	/* 128 */
                    subindex od114s_od_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 od114s_od_highestSubIndex_obj1016 = 0;
                    UNS32 od114s_od_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 od114s_od_obj1017 = 0x0;	/* 0 */
                    ODCallback_t od114s_od_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex od114s_od_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&od114s_od_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 od114s_od_highestSubIndex_obj1018 = 3; /* number of subindex - 1*/
                    UNS32 od114s_od_obj1018_Vendor_ID = 0x300;	/* 768 */
                    UNS32 od114s_od_obj1018_Product_Code = 0x4A44;	/* 19012 */
                    UNS32 od114s_od_obj1018_Revision_Number = 0x0;	/* 0 */
                    subindex od114s_od_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&od114s_od_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&od114s_od_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&od114s_od_obj1018_Revision_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 od114s_od_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 od114s_od_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 od114s_od_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 od114s_od_obj1280_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex od114s_od_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&od114s_od_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&od114s_od_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x2010 :   Mapped variable Digital In and Output */
                    UNS8 od114s_od_highestSubIndex_obj2010 = 31; /* number of subindex - 1*/
                    subindex od114s_od_Index2010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj2010 },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Input_Polarity },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Input_Simulation },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din1_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din2_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din3_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din4_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din5_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din6_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din7_Function },
                       { RO, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Input_Status },
                       { RO, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Input_Virtual_Status },
                       { RO, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Input_Sys_Status },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Output_Polarity },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Output_Simulation },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout1_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout2_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout3_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout4_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout5_Function },
                       { RO, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Output_Status },
                       { RO, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Output_Virtual_Status },
                       { RO, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Output_Sys_Status },
                       { RW, uint8, sizeof (UNS8), (void*)&Digital_In_and_Output_Compatibility_Entry1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Digital_In_and_Output_Compatibility_Entry2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Digital_In_and_Output_Compatibility_Entry3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Digital_In_and_Output_Compatibility_Entry4 },
                       { RW, uint8, sizeof (UNS8), (void*)&Digital_In_and_Output_Compatibility_Entry5 },
                       { RW, uint8, sizeof (UNS8), (void*)&Digital_In_and_Output_Compatibility_Entry6 },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Din8_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout6_Function },
                       { RW, uint16, sizeof (UNS16), (void*)&Digital_In_and_Output_Dout7_Function }
                     };

/* index 0x2501 :   Mapped variable ADC Real Data */
                    UNS8 od114s_od_highestSubIndex_obj2501 = 13; /* number of subindex - 1*/
                    subindex od114s_od_Index2501[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj2501 },
                       { RW, uint8, sizeof (UNS8), (void*)&ADC_Real_Data_Compatibility_Entry1 },
                       { RW, uint8, sizeof (UNS8), (void*)&ADC_Real_Data_Compatibility_Entry2 },
                       { RW, uint8, sizeof (UNS8), (void*)&ADC_Real_Data_Compatibility_Entry3 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC1_Data0 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC2_Data0 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC1_Data1 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC2_Data1 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC1_Data2 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC2_Data2 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC_Temperature },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC_DCBUS },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC1_Data3 },
                       { RO, uint16, sizeof (UNS16), (void*)&ADC_Real_Data_ADC1_Data4 }
                     };

/* index 0x2502 :   Mapped variable Analog Input Config */
                    UNS8 od114s_od_highestSubIndex_obj2502 = 16; /* number of subindex - 1*/
                    subindex od114s_od_Index2502[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj2502 },
                       { RW, uint16, sizeof (UNS16), (void*)&Analog_Input_Config_Analog1_Filter },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog1_Dead },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog1_Offset },
                       { RW, uint16, sizeof (UNS16), (void*)&Analog_Input_Config_Analog2_Filter },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog2_Dead },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog2_Offset },
                       { RW, uint8, sizeof (UNS8), (void*)&Analog_Input_Config_Analog_Speed_Control },
                       { RW, uint8, sizeof (UNS8), (void*)&Analog_Input_Config_Analog_Torque_Control },
                       { RW, uint8, sizeof (UNS8), (void*)&Analog_Input_Config_Analog_Max_Torque_Control },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog_Speed_Factor },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog_Torque_Factor },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog_Max_Torque_Factor },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog_Dead_High },
                       { RW, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog_Dead_Low },
                       { RO, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog1_Value },
                       { RO, int16, sizeof (INTEGER16), (void*)&Analog_Input_Config_Analog2_Value }
                     };

/* index 0x2508 :   Mapped variable Pulse Control */
                    UNS8 od114s_od_highestSubIndex_obj2508 = 15; /* number of subindex - 1*/
                    subindex od114s_od_Index2508[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj2508 },
                       { RW, int16, sizeof (INTEGER16), (void*)&Pulse_Control_Gear_Factor },
                       { RW, uint16, sizeof (UNS16), (void*)&Pulse_Control_Gear_Devider },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Control_Pulse_Mode },
                       { RW, int32, sizeof (INTEGER32), (void*)&Pulse_Control_Gear_Master_Counter },
                       { RW, int32, sizeof (INTEGER32), (void*)&Pulse_Control_Gear_Slave_Counter },
                       { RW, uint16, sizeof (UNS16), (void*)&Pulse_Control_Pulse_Filter },
                       { RW, int16, sizeof (INTEGER16), (void*)&Pulse_Control_Gear_Remainder },
                       { RW, uint16, sizeof (UNS16), (void*)&Pulse_Control_Pulse_Frequency_Check },
                       { RW, uint16, sizeof (UNS16), (void*)&Pulse_Control_Position_Reach_Time_Window },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Control_Master_Capture_Control },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Control_Compatibility_Entry1 },
                       { RO, int16, sizeof (INTEGER16), (void*)&Pulse_Control_Pulse_Master_Frequency },
                       { RO, int16, sizeof (INTEGER16), (void*)&Pulse_Control_Pulse_Slave_Frequency },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Control_Compatibility_Entry2 },
                       { RO, int32, sizeof (INTEGER32), (void*)&Pulse_Control_Master_Capture_Data }
                     };

/* index 0x2601 :   Mapped variable Error Status */
                    subindex od114s_od_Index2601[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Error_Status }
                     };

/* index 0x2602 :   Mapped variable Error Status2 */
                    subindex od114s_od_Index2602[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Error_Status2 }
                     };

/* index 0x2F81 :   Mapped variable ECAN Baudrate */
                    subindex od114s_od_Index2F81[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ECAN_Baudrate }
                     };

/* index 0x2FE0 :   Mapped variable RS232 Bandrate */
                    subindex od114s_od_Index2FE0[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&RS232_Bandrate }
                     };

/* index 0x2FE2 :   Mapped variable RS485 Bandrate */
                    subindex od114s_od_Index2FE2[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&RS485_Bandrate }
                     };

/* index 0x3011 :   Mapped variable ECAN Parameters Setting */
                    UNS8 od114s_od_highestSubIndex_obj3011 = 4; /* number of subindex - 1*/
                    subindex od114s_od_Index3011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj3011 },
                       { RW, uint8, sizeof (UNS8), (void*)&ECAN_Parameters_Setting_ECAN_Sync_Cycle },
                       { RW, uint8, sizeof (UNS8), (void*)&ECAN_Parameters_Setting_ECAN_Sync_Clock },
                       { RW, uint8, sizeof (UNS8), (void*)&ECAN_Parameters_Setting_ECAN_Flags },
                       { RW, int16, sizeof (INTEGER16), (void*)&ECAN_Parameters_Setting_ECAN_Sync_Data }
                     };

/* index 0x6004 :   Mapped variable absolute position of motor */
                    subindex od114s_od_Index6004[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&absolute_position_of_motor }
                     };

/* index 0x6007 :   Mapped variable Abort_Connection_Mode */
                    subindex od114s_od_Index6007[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Abort_Connection_Mode }
                     };

/* index 0x603F :   Mapped variable error code for DS301 */
                    subindex od114s_od_Index603F[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&error_code_for_DS301 }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex od114s_od_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex od114s_od_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword }
                     };

/* index 0x605A :   Mapped variable Quick_stop_option_code */
                    subindex od114s_od_Index605A[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Quick_stop_option_code }
                     };

/* index 0x605B :   Mapped variable Shutdown_Stop_Mode */
                    subindex od114s_od_Index605B[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Shutdown_Stop_Mode }
                     };

/* index 0x605C :   Mapped variable Disable_Stop_Mode */
                    subindex od114s_od_Index605C[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Disable_Stop_Mode }
                     };

/* index 0x605D :   Mapped variable Halt_Mode */
                    subindex od114s_od_Index605D[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Halt_Mode }
                     };

/* index 0x605E :   Mapped variable Fault_reaction_option_code */
                    subindex od114s_od_Index605E[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Fault_reaction_option_code }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex od114s_od_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation }
                     };

/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex od114s_od_Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display }
                     };

/* index 0x6063 :   Mapped variable Position_actual_value_ */
                    subindex od114s_od_Index6063[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value_ }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex od114s_od_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value }
                     };

/* index 0x6065 :   Mapped variable Maximal following error */
                    subindex od114s_od_Index6065[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_following_error }
                     };

/* index 0x6067 :   Mapped variable Position window */
                    subindex od114s_od_Index6067[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Position_window }
                     };

/* index 0x6068 :   Mapped variable Position window time */
                    subindex od114s_od_Index6068[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Position_window_time }
                     };

/* index 0x606B :   Mapped variable Velocity demand value */
                    subindex od114s_od_Index606B[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_demand_value }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex od114s_od_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value }
                     };

/* index 0x6071 :   Mapped variable Target_torque */
                    subindex od114s_od_Index6071[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Target_torque }
                     };

/* index 0x6072 :   Mapped variable Max_Torque% */
                    subindex od114s_od_Index6072[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Max_Torque }
                     };

/* index 0x6073 :   Mapped variable Max_current */
                    subindex od114s_od_Index6073[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Max_current }
                     };

/* index 0x6075 :   Mapped variable Rated_Current */
                    subindex od114s_od_Index6075[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Rated_Current }
                     };

/* index 0x6076 :   Mapped variable Rated_Torque */
                    subindex od114s_od_Index6076[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Rated_Torque }
                     };

/* index 0x6077 :   Mapped variable Actual_Torque */
                    subindex od114s_od_Index6077[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Actual_Torque }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex od114s_od_Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value }
                     };

/* index 0x6079 :   Mapped variable Real_DCBUS_mV */
                    subindex od114s_od_Index6079[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Real_DCBUS_mV }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex od114s_od_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position }
                     };

/* index 0x607C :   Mapped variable Home offset */
                    subindex od114s_od_Index607C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Home_offset }
                     };

/* index 0x607D :   Mapped variable Software position limit */
                    UNS8 od114s_od_highestSubIndex_obj607D = 2; /* number of subindex - 1*/
                    subindex od114s_od_Index607D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj607D },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Minimal_position_limit },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Maximal_position_limit }
                     };

/* index 0x607E :   Mapped variable Polarity */
                    subindex od114s_od_Index607E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Polarity }
                     };

/* index 0x607F :   Mapped variable Maximal profile velocity */
                    subindex od114s_od_Index607F[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_profile_velocity }
                     };

/* index 0x6080 :   Mapped variable Max_Speed_RPM */
                    subindex od114s_od_Index6080[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Max_Speed_RPM }
                     };

/* index 0x6081 :   Mapped variable Profile velocity */
                    subindex od114s_od_Index6081[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_velocity }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex od114s_od_Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration }
                     };

/* index 0x6084 :   Mapped variable Profile deceleration */
                    subindex od114s_od_Index6084[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_deceleration }
                     };

/* index 0x6085 :   Mapped variable Quick stop deceleration */
                    subindex od114s_od_Index6085[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Quick_stop_deceleration }
                     };

/* index 0x6098 :   Mapped variable Homing method */
                    subindex od114s_od_Index6098[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_method }
                     };

/* index 0x609A :   Mapped variable Homing acceleration */
                    subindex od114s_od_Index609A[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_acceleration }
                     };

/* index 0x60C0 :   Mapped variable Interpolation_sub_mode_select */
                    subindex od114s_od_Index60C0[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Interpolation_sub_mode_select }
                     };

/* index 0x60C1 :   Mapped variable Interpolation_data_record */
                    UNS8 od114s_od_highestSubIndex_obj60C1 = 2; /* number of subindex - 1*/
                    subindex od114s_od_Index60C1[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj60C1 },
                       { RW, int32, sizeof (INTEGER32), (void*)&Interpolation_data_record_Interpolation_data_record_x1_1 },
                       { RW, int32, sizeof (INTEGER32), (void*)&Interpolation_data_record_Interpolation_data_record_x1_2 }
                     };

/* index 0x60C2 :   Mapped variable Interpolation_time_period */
                    UNS8 od114s_od_highestSubIndex_obj60C2 = 2; /* number of subindex - 1*/
                    subindex od114s_od_Index60C2[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj60C2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_time_period_Interpolation_time_period_Interpolation_time_units_1 },
                       { RW, int8, sizeof (INTEGER8), (void*)&Interpolation_time_period_Interpolation_time_period_Interpolation_time_index }
                     };

/* index 0x60C3 :   Mapped variable Interpolation_sync_definition */
                    UNS8 od114s_od_highestSubIndex_obj60C3 = 2; /* number of subindex - 1*/
                    subindex od114s_od_Index60C3[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj60C3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_sync_definition_Interpolation_sync_definition_Synchronize_on_group_1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_sync_definition_Interpolation_sync_definition_ip_sync_every_n_event }
                     };

/* index 0x60C4 :   Mapped variable Interpolation_data_configuration */
                    UNS8 od114s_od_highestSubIndex_obj60C4 = 6; /* number of subindex - 1*/
                    subindex od114s_od_Index60C4[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj60C4 },
                       { RW, uint32, sizeof (UNS32), (void*)&Interpolation_data_configuration_Interpolation_data_configuration_Maximum_buffer_size_1 },
                       { RW, uint32, sizeof (UNS32), (void*)&Interpolation_data_configuration_Interpolation_data_configuration_Actual_buffer_size },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_data_configuration_Interpolation_data_configuration_Buffer_organization },
                       { RW, uint16, sizeof (UNS16), (void*)&Interpolation_data_configuration_Interpolation_data_configuration_Buffer_position },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_data_configuration_Interpolation_data_configuration_Size_of_data_record },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_data_configuration_Value_Description_Buffer_clear }
                     };

/* index 0x60F4 :   Mapped variable Following_error_actual_value */
                    subindex od114s_od_Index60F4[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Following_error_actual_value }
                     };

/* index 0x60F6 :   Mapped variable Current control parameter set */
                    UNS8 od114s_od_highestSubIndex_obj60F6 = 2; /* number of subindex - 1*/
                    subindex od114s_od_Index60F6[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj60F6 },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_P_gain },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_I_gain }
                     };

/* index 0x60FC :   Mapped variable Position_demand_value */
                    subindex od114s_od_Index60FC[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_demand_value }
                     };

/* index 0x60FD :   Mapped variable Digital_inputs */
                    subindex od114s_od_Index60FD[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Digital_inputs }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex od114s_od_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity }
                     };

/* index 0x6410 :   Mapped variable Motor data */
                    UNS8 od114s_od_highestSubIndex_obj6410 = 5; /* number of subindex - 1*/
                    subindex od114s_od_Index6410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&od114s_od_highestSubIndex_obj6410 },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Continous_current_limit },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Output_current_limit },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_data_Pole_pair_number },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Maximal_speed_in_current_mode },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Thermal_time_constant_winding }
                     };

/* index 0x6504 :   Mapped variable Drive_manufacturer */
                    subindex od114s_od_Index6504[] = 
                     {
                       { RO, visible_string, 30, (void*)&Drive_manufacturer }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable od114s_od_objdict[] = 
{
  { (subindex*)od114s_od_Index1000,sizeof(od114s_od_Index1000)/sizeof(od114s_od_Index1000[0]), 0x1000},
  { (subindex*)od114s_od_Index1001,sizeof(od114s_od_Index1001)/sizeof(od114s_od_Index1001[0]), 0x1001},
  { (subindex*)od114s_od_Index1005,sizeof(od114s_od_Index1005)/sizeof(od114s_od_Index1005[0]), 0x1005},
  { (subindex*)od114s_od_Index1006,sizeof(od114s_od_Index1006)/sizeof(od114s_od_Index1006[0]), 0x1006},
  { (subindex*)od114s_od_Index1008,sizeof(od114s_od_Index1008)/sizeof(od114s_od_Index1008[0]), 0x1008},
  { (subindex*)od114s_od_Index1009,sizeof(od114s_od_Index1009)/sizeof(od114s_od_Index1009[0]), 0x1009},
  { (subindex*)od114s_od_Index100A,sizeof(od114s_od_Index100A)/sizeof(od114s_od_Index100A[0]), 0x100A},
  { (subindex*)od114s_od_Index100B,sizeof(od114s_od_Index100B)/sizeof(od114s_od_Index100B[0]), 0x100B},
  { (subindex*)od114s_od_Index100C,sizeof(od114s_od_Index100C)/sizeof(od114s_od_Index100C[0]), 0x100C},
  { (subindex*)od114s_od_Index100D,sizeof(od114s_od_Index100D)/sizeof(od114s_od_Index100D[0]), 0x100D},
  { (subindex*)od114s_od_Index100E,sizeof(od114s_od_Index100E)/sizeof(od114s_od_Index100E[0]), 0x100E},
  { (subindex*)od114s_od_Index1010,sizeof(od114s_od_Index1010)/sizeof(od114s_od_Index1010[0]), 0x1010},
  { (subindex*)od114s_od_Index1011,sizeof(od114s_od_Index1011)/sizeof(od114s_od_Index1011[0]), 0x1011},
  { (subindex*)od114s_od_Index1014,sizeof(od114s_od_Index1014)/sizeof(od114s_od_Index1014[0]), 0x1014},
  { (subindex*)od114s_od_Index1017,sizeof(od114s_od_Index1017)/sizeof(od114s_od_Index1017[0]), 0x1017},
  { (subindex*)od114s_od_Index1018,sizeof(od114s_od_Index1018)/sizeof(od114s_od_Index1018[0]), 0x1018},
  { (subindex*)od114s_od_Index1280,sizeof(od114s_od_Index1280)/sizeof(od114s_od_Index1280[0]), 0x1280},
  { (subindex*)od114s_od_Index2010,sizeof(od114s_od_Index2010)/sizeof(od114s_od_Index2010[0]), 0x2010},
  { (subindex*)od114s_od_Index2501,sizeof(od114s_od_Index2501)/sizeof(od114s_od_Index2501[0]), 0x2501},
  { (subindex*)od114s_od_Index2502,sizeof(od114s_od_Index2502)/sizeof(od114s_od_Index2502[0]), 0x2502},
  { (subindex*)od114s_od_Index2508,sizeof(od114s_od_Index2508)/sizeof(od114s_od_Index2508[0]), 0x2508},
  { (subindex*)od114s_od_Index2601,sizeof(od114s_od_Index2601)/sizeof(od114s_od_Index2601[0]), 0x2601},
  { (subindex*)od114s_od_Index2602,sizeof(od114s_od_Index2602)/sizeof(od114s_od_Index2602[0]), 0x2602},
  { (subindex*)od114s_od_Index2F81,sizeof(od114s_od_Index2F81)/sizeof(od114s_od_Index2F81[0]), 0x2F81},
  { (subindex*)od114s_od_Index2FE0,sizeof(od114s_od_Index2FE0)/sizeof(od114s_od_Index2FE0[0]), 0x2FE0},
  { (subindex*)od114s_od_Index2FE2,sizeof(od114s_od_Index2FE2)/sizeof(od114s_od_Index2FE2[0]), 0x2FE2},
  { (subindex*)od114s_od_Index3011,sizeof(od114s_od_Index3011)/sizeof(od114s_od_Index3011[0]), 0x3011},
  { (subindex*)od114s_od_Index6004,sizeof(od114s_od_Index6004)/sizeof(od114s_od_Index6004[0]), 0x6004},
  { (subindex*)od114s_od_Index6007,sizeof(od114s_od_Index6007)/sizeof(od114s_od_Index6007[0]), 0x6007},
  { (subindex*)od114s_od_Index603F,sizeof(od114s_od_Index603F)/sizeof(od114s_od_Index603F[0]), 0x603F},
  { (subindex*)od114s_od_Index6040,sizeof(od114s_od_Index6040)/sizeof(od114s_od_Index6040[0]), 0x6040},
  { (subindex*)od114s_od_Index6041,sizeof(od114s_od_Index6041)/sizeof(od114s_od_Index6041[0]), 0x6041},
  { (subindex*)od114s_od_Index605A,sizeof(od114s_od_Index605A)/sizeof(od114s_od_Index605A[0]), 0x605A},
  { (subindex*)od114s_od_Index605B,sizeof(od114s_od_Index605B)/sizeof(od114s_od_Index605B[0]), 0x605B},
  { (subindex*)od114s_od_Index605C,sizeof(od114s_od_Index605C)/sizeof(od114s_od_Index605C[0]), 0x605C},
  { (subindex*)od114s_od_Index605D,sizeof(od114s_od_Index605D)/sizeof(od114s_od_Index605D[0]), 0x605D},
  { (subindex*)od114s_od_Index605E,sizeof(od114s_od_Index605E)/sizeof(od114s_od_Index605E[0]), 0x605E},
  { (subindex*)od114s_od_Index6060,sizeof(od114s_od_Index6060)/sizeof(od114s_od_Index6060[0]), 0x6060},
  { (subindex*)od114s_od_Index6061,sizeof(od114s_od_Index6061)/sizeof(od114s_od_Index6061[0]), 0x6061},
  { (subindex*)od114s_od_Index6063,sizeof(od114s_od_Index6063)/sizeof(od114s_od_Index6063[0]), 0x6063},
  { (subindex*)od114s_od_Index6064,sizeof(od114s_od_Index6064)/sizeof(od114s_od_Index6064[0]), 0x6064},
  { (subindex*)od114s_od_Index6065,sizeof(od114s_od_Index6065)/sizeof(od114s_od_Index6065[0]), 0x6065},
  { (subindex*)od114s_od_Index6067,sizeof(od114s_od_Index6067)/sizeof(od114s_od_Index6067[0]), 0x6067},
  { (subindex*)od114s_od_Index6068,sizeof(od114s_od_Index6068)/sizeof(od114s_od_Index6068[0]), 0x6068},
  { (subindex*)od114s_od_Index606B,sizeof(od114s_od_Index606B)/sizeof(od114s_od_Index606B[0]), 0x606B},
  { (subindex*)od114s_od_Index606C,sizeof(od114s_od_Index606C)/sizeof(od114s_od_Index606C[0]), 0x606C},
  { (subindex*)od114s_od_Index6071,sizeof(od114s_od_Index6071)/sizeof(od114s_od_Index6071[0]), 0x6071},
  { (subindex*)od114s_od_Index6072,sizeof(od114s_od_Index6072)/sizeof(od114s_od_Index6072[0]), 0x6072},
  { (subindex*)od114s_od_Index6073,sizeof(od114s_od_Index6073)/sizeof(od114s_od_Index6073[0]), 0x6073},
  { (subindex*)od114s_od_Index6075,sizeof(od114s_od_Index6075)/sizeof(od114s_od_Index6075[0]), 0x6075},
  { (subindex*)od114s_od_Index6076,sizeof(od114s_od_Index6076)/sizeof(od114s_od_Index6076[0]), 0x6076},
  { (subindex*)od114s_od_Index6077,sizeof(od114s_od_Index6077)/sizeof(od114s_od_Index6077[0]), 0x6077},
  { (subindex*)od114s_od_Index6078,sizeof(od114s_od_Index6078)/sizeof(od114s_od_Index6078[0]), 0x6078},
  { (subindex*)od114s_od_Index6079,sizeof(od114s_od_Index6079)/sizeof(od114s_od_Index6079[0]), 0x6079},
  { (subindex*)od114s_od_Index607A,sizeof(od114s_od_Index607A)/sizeof(od114s_od_Index607A[0]), 0x607A},
  { (subindex*)od114s_od_Index607C,sizeof(od114s_od_Index607C)/sizeof(od114s_od_Index607C[0]), 0x607C},
  { (subindex*)od114s_od_Index607D,sizeof(od114s_od_Index607D)/sizeof(od114s_od_Index607D[0]), 0x607D},
  { (subindex*)od114s_od_Index607E,sizeof(od114s_od_Index607E)/sizeof(od114s_od_Index607E[0]), 0x607E},
  { (subindex*)od114s_od_Index607F,sizeof(od114s_od_Index607F)/sizeof(od114s_od_Index607F[0]), 0x607F},
  { (subindex*)od114s_od_Index6080,sizeof(od114s_od_Index6080)/sizeof(od114s_od_Index6080[0]), 0x6080},
  { (subindex*)od114s_od_Index6081,sizeof(od114s_od_Index6081)/sizeof(od114s_od_Index6081[0]), 0x6081},
  { (subindex*)od114s_od_Index6083,sizeof(od114s_od_Index6083)/sizeof(od114s_od_Index6083[0]), 0x6083},
  { (subindex*)od114s_od_Index6084,sizeof(od114s_od_Index6084)/sizeof(od114s_od_Index6084[0]), 0x6084},
  { (subindex*)od114s_od_Index6085,sizeof(od114s_od_Index6085)/sizeof(od114s_od_Index6085[0]), 0x6085},
  { (subindex*)od114s_od_Index6098,sizeof(od114s_od_Index6098)/sizeof(od114s_od_Index6098[0]), 0x6098},
  { (subindex*)od114s_od_Index609A,sizeof(od114s_od_Index609A)/sizeof(od114s_od_Index609A[0]), 0x609A},
  { (subindex*)od114s_od_Index60C0,sizeof(od114s_od_Index60C0)/sizeof(od114s_od_Index60C0[0]), 0x60C0},
  { (subindex*)od114s_od_Index60C1,sizeof(od114s_od_Index60C1)/sizeof(od114s_od_Index60C1[0]), 0x60C1},
  { (subindex*)od114s_od_Index60C2,sizeof(od114s_od_Index60C2)/sizeof(od114s_od_Index60C2[0]), 0x60C2},
  { (subindex*)od114s_od_Index60C3,sizeof(od114s_od_Index60C3)/sizeof(od114s_od_Index60C3[0]), 0x60C3},
  { (subindex*)od114s_od_Index60C4,sizeof(od114s_od_Index60C4)/sizeof(od114s_od_Index60C4[0]), 0x60C4},
  { (subindex*)od114s_od_Index60F4,sizeof(od114s_od_Index60F4)/sizeof(od114s_od_Index60F4[0]), 0x60F4},
  { (subindex*)od114s_od_Index60F6,sizeof(od114s_od_Index60F6)/sizeof(od114s_od_Index60F6[0]), 0x60F6},
  { (subindex*)od114s_od_Index60FC,sizeof(od114s_od_Index60FC)/sizeof(od114s_od_Index60FC[0]), 0x60FC},
  { (subindex*)od114s_od_Index60FD,sizeof(od114s_od_Index60FD)/sizeof(od114s_od_Index60FD[0]), 0x60FD},
  { (subindex*)od114s_od_Index60FF,sizeof(od114s_od_Index60FF)/sizeof(od114s_od_Index60FF[0]), 0x60FF},
  { (subindex*)od114s_od_Index6410,sizeof(od114s_od_Index6410)/sizeof(od114s_od_Index6410[0]), 0x6410},
  { (subindex*)od114s_od_Index6504,sizeof(od114s_od_Index6504)/sizeof(od114s_od_Index6504[0]), 0x6504},
};

const indextable * od114s_od_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = od114s_od_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = od114s_od_Index1006_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1009: i = 5;break;
		case 0x100A: i = 6;break;
		case 0x100B: i = 7;break;
		case 0x100C: i = 8;break;
		case 0x100D: i = 9;break;
		case 0x100E: i = 10;break;
		case 0x1010: i = 11;break;
		case 0x1011: i = 12;break;
		case 0x1014: i = 13;break;
		case 0x1017: i = 14;*callbacks = od114s_od_Index1017_callbacks; break;
		case 0x1018: i = 15;break;
		case 0x1280: i = 16;break;
		case 0x2010: i = 17;break;
		case 0x2501: i = 18;break;
		case 0x2502: i = 19;break;
		case 0x2508: i = 20;break;
		case 0x2601: i = 21;break;
		case 0x2602: i = 22;break;
		case 0x2F81: i = 23;break;
		case 0x2FE0: i = 24;break;
		case 0x2FE2: i = 25;break;
		case 0x3011: i = 26;break;
		case 0x6004: i = 27;break;
		case 0x6007: i = 28;break;
		case 0x603F: i = 29;break;
		case 0x6040: i = 30;break;
		case 0x6041: i = 31;break;
		case 0x605A: i = 32;break;
		case 0x605B: i = 33;break;
		case 0x605C: i = 34;break;
		case 0x605D: i = 35;break;
		case 0x605E: i = 36;break;
		case 0x6060: i = 37;break;
		case 0x6061: i = 38;break;
		case 0x6063: i = 39;break;
		case 0x6064: i = 40;break;
		case 0x6065: i = 41;break;
		case 0x6067: i = 42;break;
		case 0x6068: i = 43;break;
		case 0x606B: i = 44;break;
		case 0x606C: i = 45;break;
		case 0x6071: i = 46;break;
		case 0x6072: i = 47;break;
		case 0x6073: i = 48;break;
		case 0x6075: i = 49;break;
		case 0x6076: i = 50;break;
		case 0x6077: i = 51;break;
		case 0x6078: i = 52;break;
		case 0x6079: i = 53;break;
		case 0x607A: i = 54;break;
		case 0x607C: i = 55;break;
		case 0x607D: i = 56;break;
		case 0x607E: i = 57;break;
		case 0x607F: i = 58;break;
		case 0x6080: i = 59;break;
		case 0x6081: i = 60;break;
		case 0x6083: i = 61;break;
		case 0x6084: i = 62;break;
		case 0x6085: i = 63;break;
		case 0x6098: i = 64;break;
		case 0x609A: i = 65;break;
		case 0x60C0: i = 66;break;
		case 0x60C1: i = 67;break;
		case 0x60C2: i = 68;break;
		case 0x60C3: i = 69;break;
		case 0x60C4: i = 70;break;
		case 0x60F4: i = 71;break;
		case 0x60F6: i = 72;break;
		case 0x60FC: i = 73;break;
		case 0x60FD: i = 74;break;
		case 0x60FF: i = 75;break;
		case 0x6410: i = 76;break;
		case 0x6504: i = 77;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &od114s_od_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status od114s_od_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index od114s_od_firstIndex = {
  0, /* SDO_SVR */
  16, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index od114s_od_lastIndex = {
  0, /* SDO_SVR */
  16, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 od114s_od_ObjdictSize = sizeof(od114s_od_objdict)/sizeof(od114s_od_objdict[0]); 

CO_Data od114s_od_Data = CANOPEN_NODE_DATA_INITIALIZER(od114s_od);

