Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
drv_common.c
""")

path = [pwd]

if IsDefined(['BSP_USING_ON_CHIP_FLASH']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

if IsDefined(['BSP_USING_UART']):
    src += ['drv_usart.c']

path = [pwd]

group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_HC32F4A'], CPPPATH = path)

Return('group')
