import os
import sys
import importlib
import importlib.util

inq_table = {}
inq_table['MODEL_STM32F301'] = 'f301'
inq_table['MODEL_STM32F302'] = 'f302'
inq_table['MODEL_STM32F303'] = 'f303'
inq_table['MODEL_STM32F318'] = 'f318'
inq_table['MODEL_STM32F328'] = 'f328'
inq_table['MODEL_STM32F334'] = 'f334'
inq_table['MODEL_STM32F358'] = 'f358'
inq_table['MODEL_STM32F373'] = 'f373'
inq_table['MODEL_STM32F378'] = 'f378'
inq_table['MODEL_STM32F398'] = 'f398'

def soc_type_inq(g):
    for inq in inq_table:
        if inq not in g:
            continue
            
        print(inq)
            
        realdir = os.path.dirname(os.path.realpath(__file__))
    
        sub_path = os.path.join(realdir, inq_table[inq])
        sub_script = os.path.join(sub_path, "SConscript")

        loader = importlib.machinery.SourceFileLoader('SConscript', sub_script)
        spec   = importlib.util.spec_from_loader(loader.name, loader)
        mod    = importlib.util.module_from_spec(spec)
        loader.exec_module(mod)
        target_path = mod.soc_type_inq(g)
        
        return target_path
    
    return None
    