from build_tools import *

pwd     = PresentDir()
src     = []
CPPPATH = [pwd + '/include']
    
if IsDefined('OS_USING_DLOG'):
    src = Glob('source/*.c')
    
    if IsDefined('DLOG_BACKEND_USING_CONSOLE'):
        src += Glob('source/backend/console_backend.c')
    
    if IsDefined('DLOG_USING_SYSLOG'):
        src += Glob('source/syslog/*.c')
        CPPPATH.append(pwd + '/include/syslog')

group = AddCodeGroup('dlog', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
