from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_SIM7070X']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/sim7070x.c')

if IsDefined(['SIM7070X_USING_GENERAL_OPS']):
    src += Glob('source/sim7070x_general.c')

if IsDefined(['SIM7070X_USING_NETSERV_OPS']):
    src += Glob('source/sim7070x_netserv.c')

if IsDefined(['SIM7070X_USING_PING_OPS']):
    src += Glob('source/sim7070x_ping.c')

if IsDefined(['SIM7070X_USING_IFCONFIG_OPS']):
    src += Glob('source/sim7070x_ifconfig.c')

if IsDefined(['SIM7070X_USING_NETCONN_OPS']):
    src += Glob('source/sim7070x_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')