# for module compiling
import os
Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()
objs = []
list = os.listdir(pwd)

# Compile only by SOC_FAMILY_BK72XX family Socs  
if (IsDefined('SOC_FAMILY_BK72XX') == False):
    #print ('IsDefined SOC_FAMILY_BK72XX')
    Return('objs')

for d in list:
    path = os.path.join(pwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
