import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = []

src += ['GD32F403_standard_peripheral/Source/gd32f403_rcu.c']
src += ['GD32F403_standard_peripheral/Source/gd32f403_misc.c']
src += ['GD32F403_standard_peripheral/Source/gd32f403_gpio.c']
if IsDefined(['OS_USING_PIN']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_exti.c']
#    src += ['GD32F403_standard_peripheral/Source/gd32f403_syscfg.c']

if IsDefined(['OS_USING_WDG']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_fwdgt.c']
    
if IsDefined(['OS_USING_SERIAL']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_usart.c']

if IsDefined(['OS_USING_ADC']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_adc.c']

if IsDefined(['OS_USING_DAC']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_dac.c']
    
if IsDefined(['OS_USING_I2C']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_i2c.c']

if IsDefined(['OS_USING_SPI']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_spi.c']
    
if IsDefined(['OS_USING_FAL']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_fmc.c']

if IsDefined(['OS_USING_DMA']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_dma.c']

if IsDefined(['BSP_USING_RTC']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_rtc.c']
    src += ['GD32F403_standard_peripheral/Source/gd32f403_pmu.c']
    
if IsDefined(['BSP_USING_TIMER']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_timer.c']	
    
if IsDefined(['BSP_USING_ETH']):
    src += ['GD32F403_standard_peripheral/Source/gd32f403_enet.c']
    
path = [pwd + '/GD32F403_standard_peripheral/Include',
    pwd + '/CMSIS/GD/gd32f4xx/Include',
    pwd + '/CMSIS']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_GD32F403'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
