from build_tools import *

pwd     = PresentDir()
src     = []
CPPPATH = [pwd + '/include']

if IsDefined('OS_USING_CLI'):
    src += Glob('source/*.c')

group = AddCodeGroup('cli', src, depend = ['OS_USING_SHELL'], CPPPATH = CPPPATH)

Return('group')
