import os
import sys
import importlib
import importlib.util    

inq_table = {}
inq_table['MODEL_STM32L422'] = 'l422'
inq_table['MODEL_STM32L443'] = 'l443'
inq_table['MODEL_STM32L462'] = 'l462'
inq_table['MODEL_STM32L475'] = 'l475'
inq_table['MODEL_STM32L4R5'] = 'l4r5'
inq_table['MODEL_STM32L4r9'] = 'l4r9'
inq_table['MODEL_STM32L496'] = 'l496'

def soc_type_inq(g):
    for inq in inq_table:
        if inq not in g:
            continue
            
        print(inq)
            
        realdir = os.path.dirname(os.path.realpath(__file__))
    
        sub_path = os.path.join(realdir, inq_table[inq])
        sub_script = os.path.join(sub_path, "SConscript")

        loader = importlib.machinery.SourceFileLoader('SConscript', sub_script)
        spec   = importlib.util.spec_from_loader(loader.name, loader)
        mod    = importlib.util.module_from_spec(spec)
        loader.exec_module(mod)
        target_path = mod.soc_type_inq(g)
        
        return target_path
    
    return None
    