import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = Split('''
HK32F103X_lib/src/hk32f10x_adc.c
HK32F103X_lib/src/hk32f10x_bkp.c
HK32F103X_lib/src/hk32f10x_can.c
HK32F103X_lib/src/hk32f10x_crc.c
HK32F103X_lib/src/hk32f10x_dac.c
HK32F103X_lib/src/hk32f10x_dbgmcu.c
HK32F103X_lib/src/hk32f10x_dma.c
HK32F103X_lib/src/hk32f10x_exti.c
HK32F103X_lib/src/hk32f10x_flash.c
HK32F103X_lib/src/hk32f10x_fsmc.c
HK32F103X_lib/src/hk32f10x_gpio.c
HK32F103X_lib/src/hk32f10x_i2c.c
HK32F103X_lib/src/hk32f10x_iwdg.c
HK32F103X_lib/src/hk32f10x_pwr.c
HK32F103X_lib/src/hk32f10x_rcc.c
HK32F103X_lib/src/hk32f10x_rtc.c
HK32F103X_lib/src/hk32f10x_sdio.c
HK32F103X_lib/src/hk32f10x_spi.c
HK32F103X_lib/src/hk32f10x_tim.c
HK32F103X_lib/src/hk32f10x_usart.c
HK32F103X_lib/src/hk32f10x_wwdg.c
HK32F103X_lib/src/misc.c
''')

#if IsDefined(['HAL_UART_MODULE_ENABLED']):
#    src += ['HK32F103X_lib/src/hk32f10x_usart.c']

path = [pwd + '/HK32F103X_lib/inc',
    pwd + '/CMSIS/HK32F1xx/Include',
    pwd + '/CMSIS/CM3/Core']

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_HK32F1'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

