import os
import osconfig
from build_tools import *


pwd = PresentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/bsp.c
CubeMX_Config/Src/stm32f0xx_it_bsp.c
CubeMX_Config/Src/stm32f0xx_hal_msp.c
CubeMX_Config/Src/system_stm32f0xx.c
''')

# path   include path in project
path =  [pwd]
path += [pwd + '/CubeMX_Config/Inc']

if osconfig.CROSS_TOOL == 'gcc':
    src += [pwd + '/startup/startup_stm32f030xc_gcc.s']
elif osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_stm32f030xc_arm.s']
elif osconfig.CROSS_TOOL == 'iar':
    src += [pwd + '/startup/startup_stm32f030xc_iar.s']

CPPDEFINES = ['STM32F030xC'] 
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
