from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_ME3630_W']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/me3630_w.c')

if IsDefined(['ME3630_W_USING_GENERAL_OPS']):
    src += Glob('source/me3630_w_general.c')

if IsDefined(['ME3630_W_USING_NETSERV_OPS']):
    src += Glob('source/me3630_w_netserv.c')

if IsDefined(['ME3630_W_USING_PING_OPS']):
    src += Glob('source/me3630_w_ping.c')

if IsDefined(['ME3630_W_USING_IFCONFIG_OPS']):
    src += Glob('source/me3630_w_ifconfig.c')

if IsDefined(['ME3630_W_USING_NETCONN_OPS']):
    src += Glob('source/me3630_w_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')