from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_M5311']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/m5311.c')
    
if IsDefined(['M5311_USING_GENERAL_OPS']):
    src += Glob('source/m5311_general.c')

if IsDefined(['M5311_USING_NETSERV_OPS']):
    src += Glob('source/m5311_netserv.c')

if IsDefined(['M5311_USING_PING_OPS']):
    src += Glob('source/m5311_ping.c')

if IsDefined(['M5311_USING_IFCONFIG_OPS']):
    src += Glob('source/m5311_ifconfig.c')

if IsDefined(['M5311_USING_NETCONN_OPS']):
    src += Glob('source/m5311_netconn.c')

if IsDefined(['M5311_USING_ONENET_NB_OPS']):
    src += Glob('source/m5311_onenet_nb.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')