Import('OS_ROOT')
Import('osconfig')
from build_tools import *

src = []
CPPDEFINES = []

pwd = PresentDir()

if IsDefined(['OS_USING_PIN', 'BSP_USING_GPIO']):
    src += ['drv_gpio.c']

if  IsDefined(['OS_USING_SERIAL', 'BSP_USING_LPUART']):
    src += ['drv_uart.c']

if  IsDefined(['OS_USING_CLOCKEVENT', 'BSP_USING_GPT']):
    src += ['drv_hwtimer.c']

if IsDefined(['OS_USING_RTC', 'BSP_USING_RTC']):
    src += ['drv_rtc.c']

if IsDefined(['OS_USING_RTC', 'BSP_USING_RTC_LP']):
    src += ['drv_rtc_lp.c']
    
if  IsDefined(['OS_USING_SPI', 'BSP_USING_LPSPI']):
    src += ['drv_spi.c']

if IsDefined('BSP_USING_SDIO'):
    src += ['drv_usdhc.c']
    
if IsDefined('BSP_SDIO_DEVICE_SDIO'):
    src += ['drv_sdio.c']
    
if IsDefined('BSP_SDIO_DEVICE_SD'):
    src += ['drv_sd.c']

if IsDefined('BSP_SDIO_DEVICE_MMC'):
    src += ['drv_mmc.c']
    
if  IsDefined(['OS_USING_I2C', 'BSP_USING_LPI2C']):
    src += ['drv_i2c.c']

if IsDefined(['OS_USING_WDG', 'BSP_USING_WDOG']):
    src += ['drv_wdg.c']

if IsDefined(['OS_USING_WDG', 'BSP_USING_RTWDOG']):
    src += ['drv_rtwdg.c']
    
if IsDefined(['OS_USING_PWM', 'BSP_USING_PWM']):
    src += ['drv_pwm.c']

if IsDefined(['OS_USING_ADC', 'BSP_USING_ADC']):
    src += ['drv_adc.c']

if IsDefined(['OS_USING_ADC', 'BSP_USING_ADC_ETC']):
    src += ['drv_adc_etc.c']
    
if IsDefined(['OS_USING_CAN', 'BSP_USING_CAN']):
    src += ['drv_can.c']
    
if IsDefined('BSP_USING_SDRAM'):
    src += ['drv_sdram.c']

if IsDefined(['OS_USING_GRAPHIC', 'BSP_USING_LCDIF']):
    src += ['drv_lcd.c']

if IsDefined(['NET_USING_LWIP', 'BSP_USING_ETH']):
    src += ['drv_eth.c']
    CPPDEFINES += ['FSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE']
    
if IsDefined(['OS_USING_SAI', 'BSP_USING_SAI']):
    src += ['drv_sai.c']
    
if IsDefined(['OS_USING_HWCRYPTO', 'BSP_USING_TRNG']):
    src += ['drv_rng.c']    

if IsDefined(['OS_USING_USB_DEVICE', 'BSP_USING_USB_DEVICE']):
    src += ['drv_usbd.c']
    
if IsDefined(['OS_USING_FAL', 'BSP_USING_NOR_FLASH']):
    if IsDefined(['SOC_IMXRT1052']):
        src += ['flash/flexspi_romapi_ops.c']
        src += ['flash/drv_norflashapi_105x.c']
    else:
        src += ['flash/drv_norflashapi.c']
    
src += ['drv_common.c']

path =  [pwd]
path += [pwd + '/flash']
 
group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_NXP_IMXRT10XX'], CPPPATH = path, CPPDEFINES=CPPDEFINES)

Return('group')
