from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_N21']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/n21.c')

if IsDefined(['N21_USING_GENERAL_OPS']):
    src += Glob('source/n21_general.c')

if IsDefined(['N21_USING_NETSERV_OPS']):
    src += Glob('source/n21_netserv.c')

if IsDefined(['N21_USING_PING_OPS']):
    src += Glob('source/n21_ping.c')

if IsDefined(['N21_USING_IFCONFIG_OPS']):
    src += Glob('source/n21_ifconfig.c')

if IsDefined(['N21_USING_NETCONN_OPS']):
    src += Glob('source/n21_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')