from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_ML302']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/ml302.c')

if IsDefined(['ML302_USING_GENERAL_OPS']):
    src += Glob('source/ml302_general.c')

if IsDefined(['ML302_USING_NETSERV_OPS']):
    src += Glob('source/ml302_netserv.c')

if IsDefined(['ML302_USING_PING_OPS']):
    src += Glob('source/ml302_ping.c')

if IsDefined(['ML302_USING_IFCONFIG_OPS']):
    src += Glob('source/ml302_ifconfig.c')

if IsDefined(['ML302_USING_NETCONN_OPS']):
    src += Glob('source/ml302_netconn.c')

#if IsDefined(['ML302_USING_MQTTC_OPS']):
#    src += Glob('source/ml302_mqttc.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')