import osconfig
Import('OS_ROOT')
from build_tools import *

# get current directory
pwd = PresentDir()

src = Split("""
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cec.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c
STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_exti.c
""")

if IsDefined(['HAL_UART_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart_ex.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart_ex.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c']

if IsDefined(['HAL_I2C_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_i2c.c']

if IsDefined(['HAL_SPI_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi_ex.c'] 
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_spi.c']

if IsDefined(['HAL_TIM_MODULE_ENABLED']) or IsDefined(['OS_USING_PWM']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_tim.c']

if IsDefined(['HAL_ADC_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_adc.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_adc_ex.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_adc.c']

if IsDefined(['HAL_DAC_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dac.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dac_ex.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dac.c']
    
if IsDefined(['HAL_RTC_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rtc.c']
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rtc_ex.c']
    
if IsDefined(['HAL_IWDG_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_iwdg.c']
    
if IsDefined(['HAL_WWDG_MODULE_ENABLED']):
    src += ['STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_wwdg.c']

path = [pwd + '/STM32G0xx_HAL_Driver/Inc',
    pwd + '/CMSIS/ST/STM32G0xx/Include',
    pwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_STM32G0'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
