# for module compiling
import os
import osconfig
Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()

group = []
src = []
path = []

group += SConscript(os.path.join(pwd, 'devices/SConscript'))
    
Return('group')
