from build_tools import *

pwd = PresentDir()
src = []
group = []

if IsDefined(['OS_USING_PIN']):
    src += ['pin.c']

if IsDefined(['BSP_USING_PIN_PCF8574']):
    src += ['pcf8574.c']
    
group = AddCodeGroup('drivers', src, depend = ['OS_USING_PIN'], CPPPATH = [pwd])

Return('group')
