from build_tools import *

pwd = PresentDir()

demo_src = Split("""
agent_tiny_demo.c
agent_tiny_report.c
agent_tiny_cmd_ioctl.c
""")

demo_path = [
    pwd
]

path = []
src = []

if IsDefined(['HUAWEI_CLOUD_MQTT_DEMO']):
    path += demo_path
    src += demo_src

group = AddCodeGroup('cloud/huawei/mqtt/demo', src, depend = ['HUAWEI_CLOUD_MQTT_DEMO'], CPPPATH = path)

Return('group')
