from build_tools import *

pwd = PresentDir()

path = []
src = []

if IsDefined(['ONEPOS_CELL_POS']):
    path += [pwd]
    src += Glob('*.c')

group = AddCodeGroup('onepos', src, depend = ['ONEPOS_CELL_POS'], CPPPATH = path)

Return('group')