from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_BC26']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/bc26.c')

if IsDefined(['BC26_USING_GENERAL_OPS']):
    src += Glob('source/bc26_general.c')

if IsDefined(['BC26_USING_NETSERV_OPS']):
    src += Glob('source/bc26_netserv.c')
    
if IsDefined(['BC26_USING_PING_OPS']):
    src += Glob('source/bc26_ping.c')
    
if IsDefined(['BC26_USING_IFCONFIG_OPS']):
    src += Glob('source/bc26_ifconfig.c')
    
if IsDefined(['BC26_USING_NETCONN_OPS']):
    src += Glob('source/bc26_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')