Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
""")

if IsDefined(['OS_USING_PIN']):
    src += ['drv_gpio.c']

if IsDefined(['BSP_USING_UART']):
    src += ['drv_uart.c']

if IsDefined(['BSP_USING_LPUART']):
    src += ['drv_lpuart.c']

if IsDefined(['OS_USING_TIMER_DRIVER', 'BSP_USING_TIM']):
    src += ['drv_hwtimer.c']

if IsDefined(['OS_USING_PWM']):
    src += ['drv_pwm.c']

#if IsDefined(['OS_USING_SPI']):
#    src += ['drv_spi.c']

if IsDefined(['OS_USING_I2C', 'OS_USING_I2C_BITOPS']):
    if IsDefined('BSP_USING_I2C1') or IsDefined('BSP_USING_I2C2') or IsDefined('BSP_USING_I2C3') or IsDefined('BSP_USING_I2C4'):
        src += ['drv_soft_i2c.c']

if IsDefined(['OS_USING_ADC']):
    src += Glob('drv_adc.c')
   

if IsDefined('BSP_USING_SDRAM'):
    src += ['drv_sdram.c']

if IsDefined('BSP_USING_LCD'):
    src += ['drv_lcd.c']

if IsDefined('BSP_USING_ONCHIP_RTC'):
    src += ['drv_rtc.c']
    
if IsDefined(['OS_USING_FAL']):
    src += ['flash/drv_flash.c']

if IsDefined(['OS_USING_WDG']):
    src += ['drv_iwdt.c']

if IsDefined(['OS_USING_LPMGR', 'OS_USING_TICKLESS_LPMGR']):
    src += ['drv_lpmgr.c']
    src += ['drv_lptim.c']


if IsDefined(['OS_USING_LCD']):
    src += ['drv_lcd.c']

src += ['drv_common.c']

path =  [pwd]

if IsDefined('OS_USING_FAL'):
    path += [pwd + '/flash']


group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_FM33G0'], CPPPATH = path)

Return('group')
