Import('OS_ROOT')
Import('osconfig')
from build_tools import *

# get current directory
pwd = PresentDir()
path =  [pwd]

src = ['system_hc32f46x.c']

group = AddCodeGroup('bsp', src, depend = ['SERIES_HC32F46'], CPPPATH = path)

Return('group')
