Import('OS_ROOT')
Import('osconfig')
from build_tools import *

# get current directory
pwd = PresentDir()
path =  [pwd]

src = ['system_hc32l07x.c']
src += ['interrupts_hc32l07x.c']

group = AddCodeGroup('bsp', src, depend = ['SERIES_HC32L07'], CPPPATH = path)

Return('group')
