from build_tools import *

pwd = PresentDir()

path = []
src = []

if IsDefined(['GNSS_RTCM_PROT']):
    path += [pwd]
    src += Glob('*.c')

group = AddCodeGroup('onepos', src, depend = ['GNSS_RTCM_PROT'], CPPPATH = path)

Return('group')