from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_ME3616']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/me3616.c')

if IsDefined(['ME3616_USING_GENERAL_OPS']):
    src += Glob('source/me3616_general.c')

if IsDefined(['ME3616_USING_NETSERV_OPS']):
    src += Glob('source/me3616_netserv.c')

if IsDefined(['ME3616_USING_PING_OPS']):
    src += Glob('source/me3616_ping.c')

if IsDefined(['ME3616_USING_IFCONFIG_OPS']):
    src += Glob('source/me3616_ifconfig.c')

if IsDefined(['ME3616_USING_NETCONN_OPS']):
    src += Glob('source/me3616_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')