from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_L610']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/l610.c')

if IsDefined(['L610_USING_GENERAL_OPS']):
    src += Glob('source/l610_general.c')

if IsDefined(['L610_USING_NETSERV_OPS']):
    src += Glob('source/l610_netserv.c')

if IsDefined(['L610_USING_PING_OPS']):
    src += Glob('source/l610_ping.c')

if IsDefined(['L610_USING_IFCONFIG_OPS']):
    src += Glob('source/l610_ifconfig.c')

if IsDefined(['L610_USING_NETCONN_OPS']):
    src += Glob('source/l610_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')