from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_M5310A']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/m5310a.c')

if IsDefined(['M5310A_USING_GENERAL_OPS']):
    src += Glob('source/m5310a_general.c')
    
if IsDefined(['M5310A_USING_NETSERV_OPS']):
    src += Glob('source/m5310a_netserv.c')
    
if IsDefined(['M5310A_USING_PING_OPS']):
    src += Glob('source/m5310a_ping.c')
    
if IsDefined(['M5310A_USING_IFCONFIG_OPS']):
    src += Glob('source/m5310a_ifconfig.c')
    
if IsDefined(['M5310A_USING_NETCONN_OPS']):
    src += Glob('source/m5310a_netconn.c')
    
if IsDefined(['M5310A_USING_ONENET_NB_OPS']):
    src += Glob('source/m5310a_onenet_nb.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')