import os
Import('osconfig')
from build_tools import *

pwd  = PresentDir()
objs = []
src  = []

pwd  = PresentDir()

list = os.listdir(pwd)
objs += AddCodeGroup('onepos', src, depend = [''], CPPPATH = [pwd])
for d in list:
    path = os.path.join(pwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')