import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = Split('''
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c
STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c
''')

if IsDefined(['HAL_DAC_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c']

if IsDefined(['HAL_UART_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c']

if IsDefined(['HAL_I2C_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c']

if IsDefined(['HAL_SPI_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi_ex.c']
    
if IsDefined(['HAL_QSPI_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c']

if IsDefined(['HAL_PCD_MODULE_ENABLED']) or IsDefined(['HAL_HCD_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c'] 
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c']

if IsDefined(['HAL_CAN_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c']

if IsDefined(['HAL_TIM_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c']

if IsDefined(['HAL_ETH_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c']

if IsDefined(['HAL_ADC_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c']

if IsDefined(['HAL_RTC_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c']

if IsDefined(['HAL_IWDG_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c']
    
if IsDefined(['HAL_WWDG_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c']

if IsDefined(['HAL_SD_MODULE_ENABLED']) or IsDefined(['HAL_MMC_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c']

if IsDefined(['HAL_SAI_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c']

if IsDefined(['HAL_NOR_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c']

if IsDefined(['HAL_NAND_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c']

if IsDefined(['HAL_SDRAM_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c']

if IsDefined(['HAL_FLASH_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c']

if IsDefined(['HAL_LTDC_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c']

if IsDefined(['HAL_DSI_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c']

if IsDefined(['HAL_DMA2D_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c']
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.c']    
    
if IsDefined(['HAL_SPDIFRX_MODULE_ENABLED']):
    src += ['STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c']
    
path = [pwd + '/STM32F7xx_HAL_Driver/Inc',
    pwd + '/CMSIS/Device/ST/STM32F7xx/Include',
    pwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_STM32F7'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

