import os
import osconfig
from build_tools import *

pwd = PresentDir()

# add general drivers
src = Split('''
board.c
hk32f0xx_it.c
system_hk32f0xx.c
''')

# path   include path in project
path =  [pwd]
path += [pwd + '/ports']

if osconfig.CROSS_TOOL == 'gcc':
    src += [pwd + '/startup/startup_hk32f031x4x6_gcc.s']
elif osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_hk32f031x4x6_arm.s']
elif osconfig.CROSS_TOOL == 'iar':
    src += [pwd + '/startup/startup_hk32f031x4x6_iar.s']

CPPDEFINES = ['HK32F031x6'] 
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
