import os
Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()
objs = []
list = os.listdir(pwd)

src = Split('''
main.c
''')

path =  [pwd]

objs += AddCodeGroup('application', src, depend = [''], CPPPATH = path)

Return('objs')
