# for network -> protocols -> pahomqtt-v1.1.0 related component related component
import os
Import('OS_ROOT')
from build_tools import *

objs = []
pwd = PresentDir()
list = os.listdir(pwd)

if IsDefined(['OS_USING_ONENET_MQTTS']):
    for d in list:
        path = os.path.join(pwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')