import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = []

src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_rcu.c']
src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_misc.c']
src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_gpio.c']
if IsDefined(['OS_USING_PIN']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_exti.c']
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_syscfg.c']

if IsDefined(['OS_USING_WDG']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_fwdgt.c']
    
if IsDefined(['OS_USING_SERIAL']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_usart.c']

if IsDefined(['OS_USING_ADC']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_adc.c']

if IsDefined(['OS_USING_DAC']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_dac.c']
    
if IsDefined(['OS_USING_I2C']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_i2c.c']

if IsDefined(['OS_USING_SPI']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_spi.c']
    
if IsDefined(['OS_USING_FAL']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_fmc.c']

if IsDefined(['OS_USING_DMA']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_dma.c']
    
if IsDefined(['BSP_USING_RTC']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_rtc.c']
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_pmu.c']
    
if IsDefined(['BSP_USING_TIMER']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_timer.c']	
    
if IsDefined(['BSP_USING_ETH']):
    src += ['GD32F4xx_standard_peripheral/Source/gd32f4xx_enet.c']
    
path = [pwd + '/GD32F4xx_standard_peripheral/Include',
    pwd + '/CMSIS/GD/gd32f4xx/Include',
    pwd + '/CMSIS']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_GD32F4XX'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
