Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
""")

if IsDefined(['OS_USING_DEVICE']):
    src += ['hc32_devices.c']

path =  [pwd]

group = AddCodeGroup('hal/devices', src, depend = ['SERIES_HC32F07'], CPPPATH = path)
group = AddCodeGroup('hal/devices', src, depend = ['SERIES_HC32F17'], CPPPATH = path)
group = AddCodeGroup('hal/devices', src, depend = ['SERIES_HC32F19'], CPPPATH = path)
group = AddCodeGroup('hal/devices', src, depend = ['SERIES_HC32L07'], CPPPATH = path)
group = AddCodeGroup('hal/devices', src, depend = ['SERIES_HC32L17'], CPPPATH = path)
group = AddCodeGroup('hal/devices', src, depend = ['SERIES_HC32L19'], CPPPATH = path)

Return('group')
