import os
import osconfig
from build_tools import *

pwd = PresentDir()

src = Split('''
board.c
''')

# path   include path in project
path =  [pwd]
path += [pwd + '/ports']

if osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_cm32m101a_arm.s']
#elif osconfig.CROSS_TOOL == 'gcc':
#    src += [pwd + '/startup/startup_cm32m101a_gcc.s']
#elif osconfig.CROSS_TOOL == 'iar':
#    src += [pwd + '/startup/startup_cm32m101a_iar.s']


CPPDEFINES = ['SOC_SERIES_CM32M1_XXX'] 
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
