import os
import osconfig
from build_tools import *

pwd = PresentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/bsp.c
CubeMX_Config/Src/stm32g0xx_it_bsp.c
CubeMX_Config/Src/stm32g0xx_hal_msp.c
CubeMX_Config/Src/system_stm32g0xx.c
''')

# path   include path in project
path =  [pwd]
path += [pwd + '/CubeMX_Config/Inc']
path += [pwd + '/ports']

if osconfig.CROSS_TOOL == 'gcc':
    src += [pwd + '/startup/startup_stm32g0b1xx_gcc.s']
elif osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_stm32g0b1xx_arm.s']
elif osconfig.CROSS_TOOL == 'iar':
    src += [pwd + '/startup/startup_stm32g0b1xx_iar.s']

CPPDEFINES = ['STM32G0B1xx'] 
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
