# for module compiling
import os
import osconfig
Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()

group = []
src = []
path = []

path = ['CMSIS/Core/Include']
path += ['devices']

group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_NXP_LPC550X_S0X'], CPPPATH = path)

group += SConscript(os.path.join(pwd, 'devices/SConscript'))
    
Return('group')
