# for module compiling
import os

from build_tools import *

pwd  = PresentDir()

CPPPATH = [pwd + "/include"]
src  = Glob('source/*.c')

group = AddCodeGroup('ramdisk', src, depend = ['OS_USING_RAMDISK'], CPPPATH = CPPPATH)

Return('group')
