Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()
src = Split("""
core/core.c
core/usbdevice.c
""")

if IsDefined('OS_USB_DEVICE_CDC'):
	src += Glob('class/cdc_vcom.c')
	
if IsDefined('OS_USB_DEVICE_HID'):
    src += Glob('class/hid.c')

if IsDefined('OS_USB_DEVICE_MSTORAGE'):
	src += Glob('class/mstorage.c')

if IsDefined('OS_USB_DEVICE_ECM'):
	src += Glob('class/ecm.c')

if IsDefined('OS_USB_DEVICE_RNDIS'):
	src += Glob('class/rndis.c')

if IsDefined('OS_USB_DEVICE_WINUSB'):
	src += Glob('class/winusb.c')
	
if IsDefined('OS_USB_DEVICE_AUDIO_MIC'):
	src += Glob('class/audio_mic.c')

if IsDefined('OS_USB_DEVICE_AUDIO_SPEAKER'):
	src += Glob('class/audio_speaker.c')

CPPPATH = [pwd]
CPPPATH = [pwd + "/../.."]
group = AddCodeGroup('drivers', src, depend = ['OS_USING_USB_DEVICE'], CPPPATH = CPPPATH)

Return('group')
