import os
import sys
import importlib
import importlib.util    

inq_table = {}
inq_table['MODEL_STM32F030'] = 'f030'
inq_table['MODEL_STM32F070'] = 'f070'
inq_table['MODEL_STM32F071'] = 'f071'
inq_table['MODEL_STM32F072'] = 'f072'
inq_table['MODEL_STM32F078'] = 'f078'
inq_table['MODEL_STM32F091'] = 'f091'
inq_table['MODEL_STM32F098'] = 'f098'
    
def soc_type_inq(g):
    for inq in inq_table:
        if inq not in g:
            continue
            
        print(inq)
            
        realdir = os.path.dirname(os.path.realpath(__file__))
    
        sub_path = os.path.join(realdir, inq_table[inq])
        sub_script = os.path.join(sub_path, "SConscript")

        loader = importlib.machinery.SourceFileLoader('SConscript', sub_script)
        spec   = importlib.util.spec_from_loader(loader.name, loader)
        mod    = importlib.util.module_from_spec(spec)
        loader.exec_module(mod)
        target_path = mod.soc_type_inq(g)
        
        return target_path
    
    return None
    