from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_SIM7600CE']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/sim7600ce.c')

if IsDefined(['SIM7600CE_USING_GENERAL_OPS']):
    src += Glob('source/sim7600ce_general.c')

if IsDefined(['SIM7600CE_USING_NETSERV_OPS']):
    src += Glob('source/sim7600ce_netserv.c')

if IsDefined(['SIM7600CE_USING_PING_OPS']):
    src += Glob('source/sim7600ce_ping.c')

if IsDefined(['SIM7600CE_USING_IFCONFIG_OPS']):
    src += Glob('source/sim7600ce_ifconfig.c')

if IsDefined(['SIM7600CE_USING_NETCONN_OPS']):
    src += Glob('source/sim7600ce_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')