#ifndef __ONEOS_CONFIG_H__
#define __ONEOS_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define BOARD_BK7231N
#define ARCH_ARM
#define ARCH_ARM_ARM9
#define ARCH_ARM_ARM968

/* Kernel */

#define OS_NAME_MAX_15
#define OS_NAME_MAX 15
#define OS_ALIGN_SIZE 4
#define OS_TASK_PRIORITY_32
#define OS_TASK_PRIORITY_MAX 32
#define OS_TICK_PER_SECOND 100
#define OS_USING_OVERFLOW_CHECK
#define OS_MAIN_TASK_STACK_SIZE 2048
#define OS_USING_HOOK
#define OS_USING_IDLE_HOOK
#define OS_IDLE_HOOK_LIST_SIZE 4
#define OS_IDLE_TASK_STACK_SIZE 512
#define OS_USING_TIMER_SOFT
#define OS_TIMER_TASK_PRIO 0
#define OS_TIMER_TASK_STACK_SIZE 2048
#define OS_USING_WORKQUEUE
#define OS_USING_SYSTEM_WORKQUEUE
#define OS_SYSTEM_WORKQUEUE_STACK_SIZE 2048
#define OS_SYSTEM_WORKQUEUE_PRIORITY 8

/* Task communication */

#define OS_USING_SEMAPHORE
#define OS_USING_MUTEX
#define OS_USING_EVENT
#define OS_USING_MAILBOX
#define OS_USING_MESSAGEQUEUE
#define OS_USING_COMPLETION
#define OS_USING_DATAQUEUE
#define OS_USING_WAITQUEUE
/* end of Task communication */

/* Memory management */

#define OS_USING_MEM_POOL
#define OS_USING_MEM_SMALL
#define OS_USING_HEAP
#define OS_MEM_STATS
/* end of Memory management */

/* Kernel console */

#define OS_USING_CONSOLE
#define OS_CONSOLE_DEVICE_NAME "uart1"
/* end of Kernel console */

/* Enable assert */

#define OS_USING_ASSERT
/* end of Enable assert */
/* end of Kernel */

/* C standard library */

#define OS_USING_LIBC
/* end of C standard library */

/* Osal */

/* POSIX compatibility layer */

#define OS_USING_POSIX
/* end of POSIX compatibility layer */

/* RT-Thread compatibility layer */

/* end of RT-Thread compatibility layer */

/* CMSIS compatibility layer */

/* end of CMSIS compatibility layer */

/* FreeRTOS compatibility layer */

/* end of FreeRTOS compatibility layer */
/* end of Osal */

/* Drivers */

#define OS_USING_DEVICE

/* HAL */

#define SOC_FAMILY_BK72XX
#define SOC_ARM9_BK7231N

/* Hardware Drivers Config */

#define BEKEN_USING_UART1
#define BEKEN_USING_UART2
#define BEKEN_USING_FLASH
#define BEKEN_USING_GPIO
#define BEKEN_USING_WLAN
#define LWIP_NETIF_HOSTNAME 1
#define BEKEN_USING_WLAN_STA
#define BEKEN_USING_WLAN_AP
#define OS_WLAN_PROT_LWIP_PBUF_FORCE
#define RT_MAIN_THREAD_STACK_SIZE 2048
/* end of Hardware Drivers Config */
/* end of HAL */

/* Audio */

/* end of Audio */

/* MISC */

/* end of MISC */

/* PIN */

#define OS_USING_PIN
#define OS_PIN_MAX_CHIP 1
/* end of PIN */

/* Serial */

#define OS_USING_SERIAL
#define OS_SERIAL_RX_BUFSZ 64
#define OS_SERIAL_TX_BUFSZ 64
/* end of Serial */

/* WDG */

/* end of WDG */

/* RTC */

#define OS_USING_RTC
#define OS_USING_SOFT_RTC
/* end of RTC */

/* CAN */

/* end of CAN */

/* I2C */

/* end of I2C */

/* SPI */

/* end of SPI */

/* FAL */

/* end of FAL */

/* RTT */

/* end of RTT */

/* Timer */

#define OS_USING_TIMER_DRIVER
#define OS_USING_CLOCKSOURCE
/* end of Timer */

/* HwCrypto */

/* end of HwCrypto */

/* SDIO */

/* end of SDIO */

/* WLAN */

#define OS_USING_WIFI
#define OS_WLAN_DEVICE_STA_NAME "w0"
#define OS_WLAN_DEVICE_AP_NAME "ap"
#define OS_WLAN_SSID_MAX_LENGTH 32
#define OS_WLAN_PASSWORD_MAX_LENGTH 32
#define OS_WLAN_DEV_EVENT_NUM 2
#define OS_WLAN_MANAGE_ENABLE
#define OS_WLAN_SCAN_WAIT_MS 10000
#define OS_WLAN_CONNECT_WAIT_MS 10000
#define OS_WLAN_SCAN_SORT
#define OS_WLAN_MSH_CMD_ENABLE
#define OS_WLAN_AUTO_CONNECT_ENABLE
#define AUTO_CONNECTION_PERIOD_MS 2000
#define OS_WLAN_CFG_ENABLE
#define OS_WLAN_CFG_INFO_MAX 3
#define OS_WLAN_PROT_ENABLE
#define OS_WLAN_PROT_NAME_LEN 8
#define OS_WLAN_PROT_MAX 2
#define OS_WLAN_DEFAULT_PROT "lwip"
#define OS_WLAN_PROT_LWIP_ENABLE
#define OS_WLAN_PROT_LWIP_NAME "lwip"
#define OS_WLAN_WORK_TASK_ENABLE
#define OS_WLAN_WORKQUEUE_TASK_NAME "wlan"
#define OS_WLAN_WORKQUEUE_TASK_SIZE 2048
#define OS_WLAN_WORKQUEUE_TASK_PRIO 15
/* end of WLAN */

/* Graphic */

/* end of Graphic */

/* Touch */

/* end of Touch */

/* Sensors */

/* end of Sensors */

/* USB */

/* end of USB */

/* Infrared */

/* end of Infrared */

/* Low power manager */

/* end of Low power manager */

/* NAND */

/* end of NAND */

/* DMA */

#define OS_USING_DMA
/* end of DMA */
/* end of Drivers */

/* Components */

/* Atest */

/* end of Atest */

/* BLE */

#define OS_USING_BLE
#define BLE_USING_NIMBLE

/* NimBLE */

#define BLE_ROLE_BROADCASTER
#define MYNEWT_VAL_BLE_ROLE_BROADCASTER 1
#define BLE_ROLE_PERIPHERAL
#define MYNEWT_VAL_BLE_ROLE_PERIPHERAL 1
#define MYNEWT_VAL_BLE_ROLE_OBSERVER 0
#define MYNEWT_VAL_BLE_ROLE_CENTRAL 0
#define MYNEWT_VAL_BLE_MAX_CONNECTIONS 1
#define MYNEWT_VAL_BLE_MAX_PERIODIC_SYNCS 1
#define BLE_WHITELIST
#define MYNEWT_VAL_BLE_WHITELIST 1
#define MYNEWT_VAL_BLE_MULTI_ADV_INSTANCES 0
#define MYNEWT_VAL_BLE_EXT_ADV 0
#define MYNEWT_VAL_BLE_PERIODIC_ADV 0
#define MYNEWT_VAL_BLE_PERIODIC_ADV_SYNC_TRANSFER 0
#define MYNEWT_VAL_BLE_EXT_ADV_MAX_SIZE 31
#define MYNEWT_VAL_BLE_VERSION 50
#define MYNEWT_VAL_BLE_ISO 0
#define MYNEWT_VAL_BLE_ISO_TEST 0
#define MYNEWT_VAL_MSYS_1_BLOCK_COUNT 16
#define MYNEWT_VAL_MSYS_1_BLOCK_SIZE 292
#define MYNEWT_VAL_MSYS_2_BLOCK_COUNT 0
#define MYNEWT_VAL_MSYS_2_BLOCK_SIZE 0

/* HOST */

#define OS_USING_NIMBLE_HOST
#define MYNEWT_VAL_BLE_HOST 1
#define NIMBLE_CFG_HOST 1
#define MYNEWT_VAL_BLE_HOST_THREAD_STACK_SIZE 2048
#define MYNEWT_VAL_BLE_HOST_THREAD_PRIORITY 3
#define MYNEWT_VAL_BLE_HS_AUTO_START 1
#define MYNEWT_VAL_BLE_HS_DEBUG 0
#define MYNEWT_VAL_BLE_HS_PHONY_HCI_ACKS 0
#define MYNEWT_VAL_BLE_HS_REQUIRE_OS 1
#define MYNEWT_VAL_BLE_MONITOR_UART 0
#define MYNEWT_VAL_BLE_MONITOR_UART_DEV "uart0"
#define MYNEWT_VAL_BLE_MONITOR_UART_BAUDRATE 1000000
#define MYNEWT_VAL_BLE_MONITOR_UART_BUFFER_SIZE 64
#define MYNEWT_VAL_BLE_MONITOR_RTT 0
#define MYNEWT_VAL_BLE_MONITOR_RTT_BUFFER_NAME "btmonitor"
#define MYNEWT_VAL_BLE_MONITOR_RTT_BUFFER_SIZE 256
#define BLE_MONITOR_RTT_BUFFERED
#define MYNEWT_VAL_BLE_MONITOR_RTT_BUFFERED 1
#define MYNEWT_VAL_BLE_MONITOR_CONSOLE_BUFFER_SIZE 128
#define MYNEWT_VAL_BLE_L2CAP_MAX_CHANS 3
#define MYNEWT_VAL_BLE_L2CAP_SIG_MAX_PROCS 1
#define BLE_L2CAP_JOIN_RX_FRAGS
#define MYNEWT_VAL_BLE_L2CAP_JOIN_RX_FRAGS 1
#define MYNEWT_VAL_BLE_L2CAP_RX_FRAG_TIMEOUT 30000
#define MYNEWT_VAL_BLE_L2CAP_COC_MAX_NUM 0
#define MYNEWT_VAL_BLE_L2CAP_COC_MPS 292
#define MYNEWT_VAL_BLE_L2CAP_ENHANCED_COC 0
#define MYNEWT_VAL_BLE_SM_LEGACY 1
#define MYNEWT_VAL_BLE_SM_SC 0
#define MYNEWT_VAL_BLE_SM_MAX_PROCS 1
#define MYNEWT_VAL_BLE_SM_IO_CAP 0x03
#define MYNEWT_VAL_BLE_SM_OOB_DATA_FLAG 0
#define MYNEWT_VAL_BLE_SM_BONDING 0
#define MYNEWT_VAL_BLE_SM_MITM 0
#define MYNEWT_VAL_BLE_SM_KEYPRESS 0
#define MYNEWT_VAL_BLE_SM_OUR_KEY_DIST 0
#define MYNEWT_VAL_BLE_SM_THEIR_KEY_DIST 0
#define MYNEWT_VAL_BLE_SM_SC_DEBUG_KEYS 0
#define MYNEWT_VAL_BLE_GAP_MAX_PENDING_CONN_PARAM_UPDATE 1
#define MYNEWT_VAL_BLE_GATT_DISC_ALL_SVCS 0
#define MYNEWT_VAL_BLE_GATT_DISC_SVC_UUID 0
#define MYNEWT_VAL_BLE_GATT_FIND_INC_SVCS 0
#define MYNEWT_VAL_BLE_GATT_DISC_ALL_CHRS 0
#define MYNEWT_VAL_BLE_GATT_DISC_CHR_UUID 0
#define MYNEWT_VAL_BLE_GATT_DISC_ALL_DSCS 0
#define MYNEWT_VAL_BLE_GATT_READ 0
#define MYNEWT_VAL_BLE_GATT_READ_UUID 0
#define MYNEWT_VAL_BLE_GATT_READ_LONG 0
#define MYNEWT_VAL_BLE_GATT_READ_MULT 0
#define MYNEWT_VAL_BLE_GATT_WRITE_NO_RSP 0
#define MYNEWT_VAL_BLE_GATT_SIGNED_WRITE 0
#define MYNEWT_VAL_BLE_GATT_WRITE 0
#define MYNEWT_VAL_BLE_GATT_WRITE_LONG 0
#define MYNEWT_VAL_BLE_GATT_WRITE_RELIABLE 0
#define BLE_GATT_NOTIFY
#define MYNEWT_VAL_BLE_GATT_NOTIFY 1
#define BLE_GATT_INDICATE
#define MYNEWT_VAL_BLE_GATT_INDICATE 1
#define MYNEWT_VAL_BLE_GATT_READ_MAX_ATTRS 8
#define MYNEWT_VAL_BLE_GATT_WRITE_MAX_ATTRS 4
#define MYNEWT_VAL_BLE_GATT_MAX_PROCS 4
#define MYNEWT_VAL_BLE_GATT_RESUME_RATE 1000
#define BLE_ATT_SVR_FIND_INFO
#define MYNEWT_VAL_BLE_ATT_SVR_FIND_INFO 1
#define BLE_ATT_SVR_FIND_TYPE
#define MYNEWT_VAL_BLE_ATT_SVR_FIND_TYPE 1
#define BLE_ATT_SVR_READ_TYPE
#define MYNEWT_VAL_BLE_ATT_SVR_READ_TYPE 1
#define BLE_ATT_SVR_READ
#define MYNEWT_VAL_BLE_ATT_SVR_READ 1
#define BLE_ATT_SVR_READ_BLOB
#define MYNEWT_VAL_BLE_ATT_SVR_READ_BLOB 1
#define BLE_ATT_SVR_READ_MULT
#define MYNEWT_VAL_BLE_ATT_SVR_READ_MULT 1
#define BLE_ATT_SVR_READ_GROUP_TYPE
#define MYNEWT_VAL_BLE_ATT_SVR_READ_GROUP_TYPE 1
#define BLE_ATT_SVR_WRITE
#define MYNEWT_VAL_BLE_ATT_SVR_WRITE 1
#define BLE_ATT_SVR_WRITE_NO_RSP
#define MYNEWT_VAL_BLE_ATT_SVR_WRITE_NO_RSP 1
#define BLE_ATT_SVR_SIGNED_WRITE
#define MYNEWT_VAL_BLE_ATT_SVR_SIGNED_WRITE 1
#define BLE_ATT_SVR_QUEUED_WRITE
#define MYNEWT_VAL_BLE_ATT_SVR_QUEUED_WRITE 1
#define BLE_ATT_SVR_NOTIFY
#define MYNEWT_VAL_BLE_ATT_SVR_NOTIFY 1
#define BLE_ATT_SVR_INDICATE
#define MYNEWT_VAL_BLE_ATT_SVR_INDICATE 1
#define MYNEWT_VAL_BLE_ATT_PREFERRED_MTU 256
#define MYNEWT_VAL_BLE_ATT_SVR_MAX_PREP_ENTRIES 64
#define MYNEWT_VAL_BLE_ATT_SVR_QUEUED_WRITE_TMO 30000
#define MYNEWT_VAL_BLE_RPA_TIMEOUT 300
#define MYNEWT_VAL_BLE_STORE_MAX_BONDS 3
#define MYNEWT_VAL_BLE_STORE_MAX_CCCDS 8
#define MYNEWT_VAL_BLE_MESH 0
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL 0
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL_ITVL 1000
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL_THRESH 2
#define MYNEWT_VAL_BLE_HS_FLOW_CTRL_TX_ON_DISCONNECT 0
#define MYNEWT_VAL_BLE_HS_STOP_ON_SHUTDOWN 1
#define MYNEWT_VAL_BLE_HS_STOP_ON_SHUTDOWN_TIMEOUT 2000
#define MYNEWT_VAL_BLE_HS_SYSINIT_STAGE 200
#define MYNEWT_VAL_BLE_HS_LOG_MOD 4
#define MYNEWT_VAL_BLE_HS_LOG_LVL 1

/* Services */

/* ans */

#define MYNEWT_VAL_BLE_SVC_ANS_NEW_ALERT_CAT 0
#define MYNEWT_VAL_BLE_SVC_ANS_UNR_ALERT_CAT 0
#define MYNEWT_VAL_BLE_SVC_ANS_SYSINIT_STAGE 303
/* end of ans */

/* bas */

#define MYNEWT_VAL_BLE_SVC_BAS_BATTERY_LEVEL_READ_PERM 0
#define MYNEWT_VAL_BLE_SVC_BAS_BATTERY_LEVEL_NOTIFY_ENABLE 1
#define MYNEWT_VAL_BLE_SVC_BAS_SYSINIT_STAGE 303
/* end of bas */

/* bleuart */

#define MYNEWT_VAL_BLEUART_MAX_INPUT 120
#define MYNEWT_VAL_BLEUART_SYSINIT_STAGE 500
/* end of bleuart */

/* dis */

#define MYNEWT_VAL_BLE_SVC_DIS_DEFAULT_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_MODEL_NUMBER_READ_PERM 0
#define MYNEWT_VAL_BLE_SVC_DIS_MODEL_NUMBER_DEFAULT "Apache Mynewt NimBLE"
#define MYNEWT_VAL_BLE_SVC_DIS_SERIAL_NUMBER_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_SERIAL_NUMBER_DEFAULT "notset"
#define MYNEWT_VAL_BLE_SVC_DIS_HARDWARE_REVISION_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_HARDWARE_REVISION_DEFAULT "notset"
#define MYNEWT_VAL_BLE_SVC_DIS_FIRMWARE_REVISION_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_FIRMWARE_REVISION_DEFAULT "notset"
#define MYNEWT_VAL_BLE_SVC_DIS_SOFTWARE_REVISION_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_SOFTWARE_REVISION_DEFAULT "notset"
#define MYNEWT_VAL_BLE_SVC_DIS_MANUFACTURER_NAME_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_MANUFACTURER_NAME_DEFAULT "notset"
#define MYNEWT_VAL_BLE_SVC_DIS_SYSTEM_ID_READ_PERM -1
#define MYNEWT_VAL_BLE_SVC_DIS_SYSTEM_ID_DEFAULT "notset"
#define MYNEWT_VAL_BLE_SVC_DIS_SYSINIT_STAGE 303
/* end of dis */

/* gap */

#define MYNEWT_VAL_BLE_SVC_GAP_DEVICE_NAME "nimble"
#define MYNEWT_VAL_BLE_SVC_GAP_DEVICE_NAME_WRITE_PERM -1
#define MYNEWT_VAL_BLE_SVC_GAP_DEVICE_NAME_MAX_LENGTH 31
#define MYNEWT_VAL_BLE_SVC_GAP_APPEARANCE 1157
#define MYNEWT_VAL_BLE_SVC_GAP_APPEARANCE_WRITE_PERM -1
#define MYNEWT_VAL_BLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL 0
#define MYNEWT_VAL_BLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL 0
#define MYNEWT_VAL_BLE_SVC_GAP_PPCP_SLAVE_LATENCY 0
#define MYNEWT_VAL_BLE_SVC_GAP_PPCP_SUPERVISION_TMO 0
#define MYNEWT_VAL_BLE_SVC_GAP_CENTRAL_ADDRESS_RESOLUTION -1
#define MYNEWT_VAL_BLE_SVC_GAP_SYSINIT_STAGE 301
/* end of gap */

/* gatt */

#define MYNEWT_VAL_BLE_SVC_GATT_SYSINIT_STAGE 302
/* end of gatt */

/* ias */

#define MYNEWT_VAL_BLE_SVC_IAS_SYSINIT_STAGE 303
/* end of ias */

/* ipss */

#define MYNEWT_VAL_BLE_SVC_IPSS_SYSINIT_STAGE 303
/* end of ipss */

/* lls */

#define MYNEWT_VAL_BLE_SVC_LLS_SYSINIT_STAGE 303
/* end of lls */

/* tps */

#define MYNEWT_VAL_BLE_SVC_TPS_SYSINIT_STAGE 303
/* end of tps */
/* end of Services */

/* Store */

/* config */

#define MYNEWT_VAL_BLE_STORE_CONFIG_PERSIST 1
#define MYNEWT_VAL_BLE_STORE_SYSINIT_STAGE 500
/* end of config */

/* ram */

#define MYNEWT_VAL_BLE_STORE_RAM_SYSINIT_STAGE 500
#define MYNEWT_VAL_BLE_STORE_RAM_DEPRECATED_FLAG 0
/* end of ram */
/* end of Store */

/* Mesh */

/* end of Mesh */
/* end of HOST */

/* Controller */

/* end of Controller */

/* Transport */

#define BLE_USING_RAM
#define MYNEWT_VAL_BLE_HCI_EVT_HI_BUF_COUNT 2
#define MYNEWT_VAL_BLE_HCI_EVT_LO_BUF_COUNT 7
#define MYNEWT_VAL_BLE_HCI_EVT_BUF_SIZE 70
#define MYNEWT_VAL_BLE_ACL_BUF_COUNT 8
#define MYNEWT_VAL_BLE_ACL_BUF_SIZE 255
#define MYNEWT_VAL_BLE_TRANS_RAM_SYSINIT_STAGE 100

/* beken-ram */

/* end of beken-ram */
/* end of Transport */

/* Drivers */

/* end of Drivers */
#define NIMBLE_CFG_TINYCRYPT
/* end of NimBLE */
/* end of BLE */

/* Cloud */

/* OneNET */

/* MQTT kit */

/* end of MQTT kit */

/* NB-IoT kit */

/* end of NB-IoT kit */

/* EDP */

/* end of EDP */
/* end of OneNET */

/* Huawei */

/* end of Huawei */

/* AWS */

/* end of AWS */

/* Aliyun */

/* end of Aliyun */
/* end of Cloud */

/* Dlog */

#define OS_USING_DLOG
#define DLOG_OUTPUT_LVL_D
#define DLOG_GLOBAL_LEVEL 7

/* Dlog backend option */

#define DLOG_BACKEND_USING_CONSOLE
/* end of Dlog backend option */
#define DLOG_USING_FILTER

/* Log format */

#define DLOG_USING_COLOR
#define DLOG_OUTPUT_TIME_INFO
#define DLOG_OUTPUT_LEVEL_INFO
#define DLOG_OUTPUT_TAG_INFO
/* end of Log format */
/* end of Dlog */

/* Network */

/* Acw */

/* end of Acw */

/* ANDLINK */

/* end of ANDLINK */

/* LwIP */

#define NET_USING_LWIP
#define NET_USING_LWIP202
#define LWIP_USING_IGMP
#define LWIP_USING_ICMP
#define LWIP_USING_DNS
#define LWIP_USING_DHCP
#define IP_SOF_BROADCAST 1
#define IP_SOF_BROADCAST_RECV 1

/* Static IPv4 Address */

#define LWIP_STATIC_IPADDR "192.168.1.30"
#define LWIP_STATIC_GWADDR "192.168.1.1"
#define LWIP_STATIC_MSKADDR "255.255.255.0"
/* end of Static IPv4 Address */
#define LWIP_USING_UDP
#define LWIP_USING_TCP
#define LWIP_USING_RAW
#define LWIP_MEMP_NUM_NETCONN 8
#define LWIP_PBUF_NUM 8
#define LWIP_RAW_PCB_NUM 4
#define LWIP_UDP_PCB_NUM 6
#define LWIP_TCP_PCB_NUM 4
#define LWIP_TCP_SEG_NUM 40
#define LWIP_TCP_SND_BUF 4096
#define LWIP_TCP_WND_SIZE 4096
#define LWIP_TCP_TASK_PRIORITY 10
#define LWIP_TCP_TASK_MBOX_SIZE 8
#define LWIP_TCP_TASK_STACKSIZE 4096
#define LWIP_NO_RX_TASK
#define LWIP_NO_TX_TASK
#define LWIP_ETH_TASK_PRIORITY 12
#define LWIP_ETH_TASK_STACKSIZE 1024
#define LWIP_ETH_TASK_MBOX_SIZE 8
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define SO_REUSE 1
#define LWIP_SO_RCVTIMEO 1
#define LWIP_SO_SNDTIMEO 1
#define LWIP_SO_RCVBUF 1
#define LWIP_ENABLE_NETIF_LOOPBACK
#define LWIP_NETIF_LOOPBACK 1
#define LWIP_USING_PING
/* end of LwIP */

/* Molink */

/* end of Molink */

/* OTA */

/* Fota by CMIOT */

/* end of Fota by CMIOT */
/* end of OTA */

/* Protocols */

/* LWM2M */

/* end of LWM2M */

/* CoAP */

/* end of CoAP */

/* MQTT */

/* end of MQTT */

/* Websocket */

/* end of Websocket */

/* Httpclient */

/* end of Httpclient */
/* end of Protocols */

/* Socket */

#define NET_USING_BSD
#define BSD_USING_LWIP
/* end of Socket */

/* Tools */

/* end of Tools */
/* end of Network */

/* Security */

/* end of Security */

/* Shell */

#define OS_USING_SHELL
#define SHELL_TASK_NAME "tshell"
#define SHELL_TASK_PRIORITY 20
#define SHELL_TASK_STACK_SIZE 4096
#define SHELL_USING_HISTORY
#define SHELL_HISTORY_LINES 5
#define SHELL_USING_DESCRIPTION
#define SHELL_CMD_SIZE 80
#define SHELL_ARG_MAX 10
/* end of Shell */

/* FileSystem */

#define OS_USING_VFS
#define VFS_USING_WORKDIR
#define VFS_FILESYSTEMS_MAX 2
#define VFS_FILESYSTEM_TYPES_MAX 2
#define VFS_FD_MAX 16
#define OS_USING_VFS_DEVFS
/* end of FileSystem */

/* GUI */

/* end of GUI */

/* OnePos */

/* end of OnePos */

/* Ramdisk */

/* end of Ramdisk */

/* Diagnose */

/* end of Diagnose */

/* U+ */

/* end of U+ */
/* end of Components */

/* Thirdparty */

/* Character Conversion */

/* end of Character Conversion */

/* MicroPython */

/* end of MicroPython */

/* cJSON */

#define PKG_USING_CJSON
/* end of cJSON */

/* Easyflash */

#define PKG_USING_EASYFLASH
#define PKG_EASYFLASH_ENV_SETTING_SIZE 1024
#define PKG_EASYFLASH_ERASE_GRAN 4096
#define PKG_EASYFLASH_START_ADDR 2088960
/* end of Easyflash */

/* Netutils */

/* NTP */

/* end of NTP */
/* end of Netutils */

/* ttsAisound */

/* end of ttsAisound */

/* WebClient */

/* end of WebClient */
/* end of Thirdparty */

/* Boot Config */

/* end of Boot Config */

/* Debug */

#define LOG_BUFF_SIZE_256
#define OS_LOG_BUFF_SIZE 256
/* end of Debug */

#endif /* __ONEOS_CONFIG_H__ */

