# for module compiling
import os
from build_tools import *

pwd     = PresentDir()
objs 	= []
list 	= os.listdir(pwd)

if IsDefined('MANUFACTOR_STM32'):
    for d in list:
        path = os.path.join(pwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
Return('objs')
