import os
import sys
import importlib
import importlib.util


target_script = "../templates/x1000e-common/generate.py"

def soc_type_inq(g):
    target_path = None

    for soc_type in g:
        if 'TEMP_' in soc_type:
            loader = importlib.machinery.SourceFileLoader(os.path.basename(target_script), target_script)
            spec   = importlib.util.spec_from_loader(loader.name, loader)
            mod    = importlib.util.module_from_spec(spec)
            loader.exec_module(mod)
            target_path = mod.template(soc_type[5:])

    return target_path



