from build_tools import *
Import('OS_ROOT')

cwd = PresentDir()

src = Glob('*.c')
path = []
path += [cwd + '/']


vad_lib_name = 'vad'

libs = [vad_lib_name]
libpath = [cwd + '/']


group_use_lib = AddCodeGroup('beken_vad_lib', [], depend = ['SOC_FAMILY_BK72XX'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

group_build_lib = AddCodeGroup('beken_vad', src, depend = ['BUILD_LIB'], CPPPATH = path, LIBS = libs, LIBPATH = libpath, LIBNAME = 'lib' + vad_lib_name + '.a')

group = group_use_lib + group_build_lib


Return('group')
