Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
drv_common.c
drv_interrupt.c
""")

if IsDefined(['OS_USING_PIN']):
    src += ['drv_gpio.c']
    
if IsDefined(['BSP_USING_UART']):
    src += ['drv_uart.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_LPUART']):
    src += ['drv_lpuart.c']
    
if IsDefined(['OS_USING_TIMER']):
    src += ['drv_hwtimer.c']

if IsDefined(['BSP_USING_RTC']):
    src += ['drv_rtc.c']
    
if IsDefined(['BSP_USING_ADC']):
    src += ['drv_adc.c']
    
if IsDefined(['BSP_USING_WDG']):
    src += ['drv_iwdg.c']
    
if IsDefined(['BSP_USING_I2C']):
    src += ['drv_i2c.c']
    
path =  [pwd]

group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_FM33LG0'], CPPPATH = path)

Return('group')
