from build_tools import *

pwd = PresentDir()

objs = []

if not IsDefined(['MOLINK_USING_CLM920RV3']):
    Return('objs')

path = []
src = []

path += [pwd + '/include']
src += Glob('source/clm920rv3.c')

if IsDefined(['CLM920RV3_USING_GENERAL_OPS']):
    src += Glob('source/clm920rv3_general.c')
    
if IsDefined(['CLM920RV3_USING_NETSERV_OPS']):
    src += Glob('source/clm920rv3_netserv.c')
    
if IsDefined(['CLM920RV3_USING_PING_OPS']):
    src += Glob('source/clm920rv3_ping.c')
    
if IsDefined(['CLM920RV3_USING_IFCONFIG_OPS']):
    src += Glob('source/clm920rv3_ifconfig.c')
    
if IsDefined(['CLM920RV3_USING_NETCONN_OPS']):
    src += Glob('source/clm920rv3_netconn.c')

group = AddCodeGroup('molink', src, depend = ['NET_USING_MOLINK'], CPPPATH = path)

Return('group')