Import('osconfig')
from build_tools import *

pwd  = PresentDir()
src  = []
group = []
path = [pwd]

if IsDefined(['ARCH_MIPS_SOC_LS1B']) == False:
    Return('group')

# The set of source files associated with this SConscript file.
src += Glob('*.c')
src += Glob('*.cpp')
src += Glob('*_gcc.S')


group = AddCodeGroup('cpu', src, depend = [''], CPPPATH = path)

Return('group')

