import os
Import('osconfig')
from build_tools import *

objs = []

if not IsDefined(['NET_USING_MOLINK']):
    Return('objs')


pwd  = PresentDir()

list = os.listdir(pwd)
for d in list:
    path = os.path.join(pwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')