import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = []

src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_rcu.c']
src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_misc.c']
src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_gpio.c']
if IsDefined(['OS_USING_PIN']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_exti.c']
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_syscfg.c']

if IsDefined(['OS_USING_WDG']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_fwdgt.c']
    
if IsDefined(['OS_USING_SERIAL']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_usart.c']

if IsDefined(['OS_USING_ADC']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_adc.c']

if IsDefined(['OS_USING_DAC']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_dac.c']
    
if IsDefined(['OS_USING_I2C']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_i2c.c']

if IsDefined(['OS_USING_SPI']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_spi.c']
    
if IsDefined(['OS_USING_FAL']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_fmc.c']

if IsDefined(['BSP_USING_RTC']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_rtc.c']
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_bkp.c']
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_pmu.c']
    
if IsDefined(['OS_USING_DMA']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_dma.c']
    
    
if IsDefined(['HAL_HCD_MODULE_ENABLED']) or IsDefined(['HAL_PCD_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_hcd.c'] 
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_pcd.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_pcd_ex.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_ll_usb.c']

if IsDefined(['HAL_CAN_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_can.c']

if IsDefined(['HAL_TIM_MODULE_ENABLED']) or IsDefined(['OS_USING_PWM']) or IsDefined(['OS_USING_INPUT_CAPTURE']) or IsDefined(['OS_USING_PULSE_ENCODER'])or IsDefined(['OS_USING_INFRARED']) or IsDefined(['OS_USING_LPMGR']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_lptim.c']
    
if IsDefined(['BSP_USING_TIMER']):
    src += ['GD32F3x0_standard_peripheral/Source/gd32f3x0_timer.c']

if IsDefined(['HAL_ADC_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_adc.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_adc_ex.c']

if IsDefined(['HAL_IWDG_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_iwdg.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_wwdg.c']

#if IsDefined(['HAL_SD_MODULE_ENABLED']) or (['HAL_MMC_MODULE_ENABLED']):
#    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_sd.c']
#    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_sd_ex.c']
#    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_ll_sdmmc.c']

if IsDefined(['HAL_SAI_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_sai.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_sai_ex.c']

if IsDefined(['HAL_NOR_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_nor.c']

if IsDefined(['HAL_NAND_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_nand.c']

if IsDefined(['HAL_FLASH_MODULE_ENABLED']) or IsDefined(['PKG_USING_FAL']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_flash.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_flash_ex.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_flash_ramfunc.c']

if IsDefined(['HAL_SRAM_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_sram.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_ll_fmc.c']
	
if IsDefined(['HAL_GFXMMU_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_gfxmmu.c']

if IsDefined(['HAL_DSI_MODULE_ENABLED']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_dsi.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_dma2d.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_ll_dma2d.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_ltdc.c']
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_ltdc_ex.c']
	
if IsDefined(['BSP_USING_SRAM']):
    src += ['GD32F3x0_standard_peripheral/Source/stm32l4xx_hal_sram.c']	
	
	

path = [pwd + '/GD32F3x0_standard_peripheral/Include',
    pwd + '/CMSIS/GD/GD32F3x0/Include',
    pwd + '/CMSIS']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_GD32F3X0'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
