# for module compiling
import os
Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()
objs = []
list = os.listdir(pwd)

for d in list:
    path = os.path.join(pwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

src = []
path = [pwd + '/CMSIS/Core/Include']
objs += AddCodeGroup('hal', src, depend = ['SERIES_HC32L17'], CPPPATH = path)

Return('objs')
