import os
import osconfig
from build_tools import *

pwd = PresentDir()
LIBS    = []
LIBPATH = []

# add general drivers
src = Split('''
board.c
CubeMX_Config/Core/Src/bsp.c
CubeMX_Config/Core/Src/stm32f0xx_it_bsp.c
CubeMX_Config/Core/Src/stm32f0xx_hal_msp.c
CubeMX_Config/Core/Src/system_stm32f0xx.c
''')

# path   include path in project
path =  [pwd]
path += [pwd + '/CubeMX_Config/Core/Inc']
path += [pwd + '/ports']
path += [pwd + '/packages']

if osconfig.CROSS_TOOL == 'gcc':
    src += [pwd + '/startup/startup_stm32f070xb_gcc.s']
elif osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_stm32f070xb_arm.s']
elif osconfig.CROSS_TOOL == 'iar':
    src += [pwd + '/startup/startup_stm32f070xb_iar.s']

CPPDEFINES = ['STM32F070xx']
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
