from build_tools import *

pwd = PresentDir()

path = []
src = []

if IsDefined(['GNSS_USING_MX']):
    path += [pwd]
    src += Glob('*.c')

group = AddCodeGroup('onepos', src, depend = ['GNSS_USING_MX'], CPPPATH = path)

Return('group')