import os
import osconfig
from build_tools import *

pwd = PresentDir()

# add general drivers
src = Split('''
board.c
''')

# path   include path in project
path =  [pwd]
path += ['../']
path += [pwd + '/ports']
path += [pwd + '/peripheral']

if osconfig.CROSS_TOOL == 'gcc':
    src += [pwd + '/startup/startup_fm33lg0xx_gcc.s']
elif osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_fm33lg0xx_arm.s']
elif osconfig.CROSS_TOOL == 'iar':
    src += [pwd + '/startup/startup_fm33lg0xx_iar.s']

CPPDEFINES = ['FM33LG0XX']
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
