import osconfig
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.

src = Split('''
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rng.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c
''')
 
if IsDefined(['HAL_UART_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_usart.c']
    
if IsDefined(['HAL_I2C_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c']

if IsDefined(['HAL_SPI_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_qspi.c']

if IsDefined(['HAL_HCD_MODULE_ENABLED']) or IsDefined(['HAL_PCD_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_hcd.c'] 
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usb.c']

if IsDefined(['HAL_CAN_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_can.c']

if IsDefined(['HAL_TIM_MODULE_ENABLED']) or IsDefined(['OS_USING_PWM']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c']

if IsDefined(['HAL_ADC_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c']

if IsDefined(['HAL_DAC_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac_ex.c']

if IsDefined(['HAL_RTC_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c']

if IsDefined(['HAL_IWDG_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c']
    
if IsDefined(['HAL_WWDG_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_wwdg.c']

if IsDefined(['HAL_SD_MODULE_ENABLED','HAL_MMC_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sd.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sd_ex.c']

if IsDefined(['HAL_SAI_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sai.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sai_ex.c']

if IsDefined(['HAL_NOR_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_nor.c']

if IsDefined(['HAL_NAND_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_nand.c']

if IsDefined(['HAL_FLASH_MODULE_ENABLED']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c']

path = [pwd + '/STM32L0xx_HAL_Driver/Inc',
    pwd + '/CMSIS/Device/ST/STM32L0xx/Include',
    pwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/lowlevel', src, depend = ['SERIES_STM32L0'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
